export const createDados = {
  'site': {
    'name': 'English Class',
    'slug': 'english',
    'pages': [
      { 'name': 'Review', 'url': '/lesson' },
      {
        'name': 'Dark Yellow',
        'menu': [
          { 'name': 'Lesson 1A', 'url': '/vocabulary?class=0' },
          { 'name': 'Lesson 1B', 'url': '/vocabulary?class=1' },
          { 'name': 'Lesson 1C', 'url': '/vocabulary?class=2' },
          { 'name': 'Lesson 2A', 'url': '/lesson?class=3' },
          { 'name': 'Lesson 2B', 'url': '/lesson?class=4' },
          { 'name': 'Lesson 2C', 'url': '/vocabulary?class=5' },
          { 'name': 'Lesson 3A', 'url': '/vocabulary?class=6' },
          { 'name': 'Lesson 3B', 'url': '/vocabulary?class=7' },
          { 'name': 'Lesson 3C', 'url': '/vocabulary?class=8' },
          { 'name': 'Lesson 4A', 'url': '/vocabulary?class=9' },
          { 'name': 'Lesson 4B', 'url': '/vocabulary?class=10' },
          { 'name': 'Lesson 4C', 'url': '/vocabulary?class=11' }
        ]
      },
      {
        'name': 'Orange',
        'menu': [
          { 'name': 'Lesson 1A', 'url': '/vocabulary?class=12' },
          { 'name': 'Lesson 1B', 'url': '/vocabulary?class=13' },
          { 'name': 'Lesson 1C', 'url': '/vocabulary?class=14' },
          { 'name': 'Lesson 2A', 'url': '/vocabulary?class=15' },
          { 'name': 'Lesson 2B', 'url': '/vocabulary?class=16' },
          { 'name': 'Lesson 2C', 'url': '/vocabulary?class=17' },
          { 'name': 'Lesson 2D', 'url': '/vocabulary?class=18' },
          { 'name': 'Lesson 3A', 'url': '/vocabulary?class=19' },
          { 'name': 'Lesson 3B', 'url': '/vocabulary?class=20' }
        ]
      },
      {
        'name': 'Light Green',
        'menu': [
          { 'name': 'Lesson 1A', 'url': '/vocabulary?class=21' },
          { 'name': 'Lesson 1B', 'url': '/vocabulary?class=22' },
          { 'name': 'Lesson 2A', 'url': '/vocabulary?class=23' },
          { 'name': 'Lesson 2B', 'url': '/vocabulary?class=24' }
        ]
      }
    ]
  },
  'review': [
    {
      'title': 'Translate the following sentences into English and rewrite them with each substitution:',
      'questions': [
        { 'q': 'EU ESTOU COM FOME. VOCÊ PODERIA COZINHAR PARA MIM? (PARA NÓS)', 'r': 'I\'M HUNGRY. COULD YOU COOK FOR ME?<br> I\'M HUNGRY. COULD YOU COOK FOR US?', 'visible': false },
        { 'q': 'ONDE VOCÊ QUER COLOCAR O LENÇOL? (COBERTOR / TRAVESSEIRO / FRONHA)', 'r': 'WHERE DO YOU WANT TO PUT THE SHEET?<br> WHERE DO YOU WANT TO PUT THE BLANKET?<br> WHERE DO YOU WANT TO PUT THE PILLOW?<br> WHERE DO YOU WANT TO PUT THE PILLOWCASE?', 'visible': false },
        { 'q': 'ELA NÃO GOSTA DE LAVAR A FRIGIDEIRA. (PANELA / ASSADEIRA / A LOUÇA)', 'r': 'SHE DOESN\'T LIKE TO WASH THE FRYING PAN.<br> SHE DOESN\'T LIKE TO WASH THE PAN.<br> SHE DOESN\'T LIKE TO WASH THE BAKING PAN.<br> SHE DOESN\'T LIKE TO WASH THE DISHES.', 'visible': false },
        { 'q': 'EU PRECISO COMPRAR CREME APÓS BARBA. (CREME DE BARBEAR / LÂMINA DE BARBEAR)', 'r': 'I NEED TO BUY AFTER SHAVE.<br> I NEED TO BUY SHAVING CREAM.<br> I NEED TO BUY A RAZOR.', 'visible': false },
        { 'q': 'VOCÊ PREFERE TOMAR BANHO DE BANHEIRA OU DE CHUVEIRO? (ELA / ELE / ELES)', 'r': 'DO YOU PREFER TO TAKE A BATH OR TO TAKE A SHOWER?<br> DOES SHE PREFER TO TAKE A BATH OR TO TAKE A SHOWER?<br> DOES HE PREFER TO TAKE A BATH OR TO TAKE A SHOWER?<br> DO THEY PREFER TO TAKE A BATH OR TO TAKE A SHOWER?', 'visible': false },
        { 'q': 'HÁ UM CARRO EM FRENTE À NOSSA ESCOLA. (ATRÁS DE / AO LADO DE / DO OUTRO LADO DA RUA)', 'r': 'THERE IS A CAR IN FRONT OF OUR SCHOOL.<br> THERE IS A CAR BEHIND OUR SCHOOL.<br> THERE IS A CAR BESIDE OUR SCHOOL.<br> THERE IS A CAR ACROSS FROM OUR SCHOOL.', 'visible': false },
        { 'q': 'ONDE É O MUSEU? (TEATRO / PREFEITURA / DELEGACIA)', 'r': 'WHERE IS THE MUSEUM?<br> WHERE IS THE THEATER?<br> WHERE IS THE CITY HALL?<br> WHERE IS THE POLICE STATION?', 'visible': false },
        { 'q': 'ELE GOSTA DE ANDAR DE MANHÃ. (DE TARDE / À NOITE)', 'r': 'HE LIKES TO WALK IN THE MORNING.<br> HE LIKES TO WALK IN THE AFTERNOON.<br> HE LIKES TO WALK AT NIGHT.', 'visible': false },
        { 'q': 'ELA QUER ALUGAR SUA (DELA) CASA NOVAMENTE. (ELE DELE / NÓS NOSSA / ELES DELES)', 'r': 'SHE WANTS TO RENT HER HOUSE AGAIN.<br> HE WANTS TO RENT HIS HOUSE AGAIN.<br> WE WANT TO RENT OUR HOUSE AGAIN.<br> THEY WANT TO RENT THEIR HOUSE AGAIN.', 'visible': false },
        { 'q': 'QUANTO CUSTA ESTA CAMISA VERMELHA? (AZUL / BRANCA / PRETA)', 'r': 'HOW MUCH DOES THIS RED SHIRT COST?<br> HOW MUCH DOES THIS BLUE SHIRT COST?<br> HOW MUCH DOES THIS WHITE SHIRT COST?<br> HOW MUCH DOES THIS BLACK SHIRT COST?', 'visible': false },
        { 'q': 'POSSO TE LIGAR NA SEGUNDA? (TERÇA / SEXTA / SÁBADO)', 'r': 'CAN I CALL YOU ON MONDAY?<br> CAN I CALL YOU ON TUESDAY?<br> CAN I CALL YOU ON FRIDAY?<br> CAN I CALL YOU ON SATURDAY?', 'visible': false },
        { 'q': 'VOCÊ QUER ENVIAR ESTE EMAIL PARA SEU PAI, TAMBÉM? (MENSAGEM / PACOTE)', 'r': 'DO YOU WANT TO SEND THIS EMAIL TO YOUR FATHER TOO?<br> DO YOU WANT TO SEND THIS MESSAGE TO YOUR FATHER TOO?<br> DO YOU WANT TO SEND THIS PACKAGE TO YOUR FATHER TOO?<br>', 'visible': false },
        { 'q': 'VOCÊ PODE ME EXPLICAR ISTO? (A ELA / A ELE / A ELES)', 'r': 'CAN YOU EXPLAIN THIS TO ME?<br>CAN YOU EXPLAIN THIS TO HER?<br>CAN YOU EXPLAIN THIS TO HIM?<br>CAN YOU EXPLAIN THIS TO THEM?', 'visible': false },
        { 'q': 'ELA GERALMENTE VAI À ESCOLA A PÉ. (NUNCA / RARAMENTE / QUASE NUNCA)', 'r': 'SHE USUALLY GOES TO SCHOOL ON FOOT.<br> SHE NEVER GOES TO SCHOOL ON FOOT.<br> SHE SELDOM GOES TO SCHOOL ON FOOT.<br> SHE HARDLY EVER GOES TO SCHOOL ON FOOT.', 'visible': false },
        { 'q': 'VOCÊ GERALMENTE PENTEIA OU ESCOVA SEU CABELO? (ELE DELE / ELES DELES)', 'r': 'DO YOU USUALLY COMB OR BRUSH YOUR HAIR?<br> DOES HE USUALLY COMB OR BRUSH HIS HAIR?<br> DO THEY USUALLY COMB OR BRUSH THEIR HAIR?', 'visible': false },
        { 'q': 'VOCÊ PODERIA LAVAR A TOALHA DE ROSTO? (TOALHA DE BANHO / MINHAS ROUPAS)', 'r': 'COULD YOU WASH THE HAND TOWEL?<br> COULD YOU WASH THE BATH TOWEL?<br> COULD YOU WASH MY CLOTHES?', 'visible': false },
        { 'q': 'HÁ MUITAS PESSOAS NO MEIO DA RUA. (NA FRENTE DO POSTO DE GASOLINA / EMBAIXO DA ÁRVORE)', 'r': 'THERE ARE MANY PEOPLE IN THE MIDDLE OF THE STREET.<br> THERE ARE MANY PEOPLE IN FRONT OF THE GAS STATION.<br> THERE ARE MANY PEOPLE UNDER THE TREE.', 'visible': false },
        { 'q': 'ONDE É A BANCA DE JORNAL? DO LADO DIREITO. (DO LADO ESQUERDO)', 'r': 'WHERE IS THE NEWSSTAND? ON THE RIGHT HAND SIDE.<br> WHERE IS THE NEWSSTAND? ON THE LEFT HAND SIDE.', 'visible': false },
        { 'q': 'ONDE É O POSTO DE GASOLINA? ANDE DUAS QUADRAS E VIRE À ESQUERDA. (DIREITA)', 'r': 'WHERE IS THE GAS STATION? WALK (FOR) TWO BLOCKS AND TURN LEFT.<br> WHERE IS THE GAS STATION? WALK (FOR) TWO BLOCKS AND TURN RIGHT.', 'visible': false },
        { 'q': 'QUE HORAS SÃO? JÁ SÃO 7:00. (3:30 PM / 12:00 AM / 8:45 AM / 2:05 PM / 12:00 PM)', 'r': 'WHAT TIME IS IT? IT\'S ALREADY SEVEN O\'CLOCK.<br> WHAT TIME IS IT? IT\'S ALREADY THREE THIRTY PM.<br> WHAT TIME IS IT? IT\'S ALREADY (TWELVE) MIDNIGHT.<br> WHAT TIME IS IT? IT\'S ALREADY EIGHT FORTY-FIVE AM.<br> WHAT TIME IS IT? IT\'S ALREADY TWO-OH-FIVE PM.<br> WHAT TIME IS IT? IT\'S ALREADY (TWELVE) NOON.', 'visible': false },
        { 'q': 'COMO VOCÊ QUER PAGAR? À VISTA. (ELA / ELE / ELES)', 'r': 'HOW DO YOU WANT TO PAY? CASH.<br> HOW DOES SHE WANT TO PAY? CASH.<br> HOW DOES HE WANT TO PAY? CASH.<br> HOW DO THEY WANT TO PAY? CASH.', 'visible': false },
        { 'q': 'ELES NÃO CONSEGUEM CANTAR. E VOCÊ? (MERGULHAR / NADAR / COZINHAR)', 'r': 'THEY CAN\'T SING. AND YOU? / WHAT ABOUT YOU?<br> THEY CAN\'T DIVE. AND YOU? / WHAT ABOUT YOU?<br> THEY CAN\'T SWIM. AND YOU? / WHAT ABOUT YOU?<br> THEY CAN\'T COOK. AND YOU? / WHAT ABOUT YOU?', 'visible': false },
        { 'q': 'EU QUERO TE PEDIR UM FAVOR. (NÓS / ELES / ELA)', 'r': 'I WANT TO ASK YOU A FAVOR.<br> WE WANT TO ASK YOU A FAVOR.<br> THEY WANT TO ASK YOU A FAVOR.<br> SHE WANTS TO ASK YOU A FAVOR.', 'visible': false },
        { 'q': 'VOCÊ PODERIA LIGAR PARA ELA? (PARA ELE / PARA ELES / PARA MINHA MÃE)', 'r': 'COULD YOU CALL HER?<br> COULD YOU CALL HIM?<br> COULD YOU CALL THEM?<br> COULD YOU CALL MY MOTHER?', 'visible': false },
        { 'q': 'EU TENHO QUE COMPRAR UM FORNO NOVO. (FOGÃO / GELADEIRA / MICROONDAS)', 'r': 'I HAVE TO BUY A NEW OVEN.<br> I HAVE TO BUY A NEW STOVE.<br> I HAVE TO BUY A NEW FRIDGE.<br> I HAVE TO BUY A NEW MICROWAVE.', 'visible': false },
        { 'q': 'MEXA A SOPA PARA MIM, POR FAVOR. (SUCO)', 'r': 'STIR THE SOUP FOR ME, PLEASE.<br> STIR THE JUICE FOR ME, PLEASE.', 'visible': false },
        { 'q': 'VOCÊ TEM QUE RESPONDER ESTAS PERGUNTAS. (ELA / ELE / NÓS)', 'r': 'YOU HAVE TO ANSWER THESE QUESTIONS.<br> SHE HAS TO ANSWER THESE QUESTIONS.<br> HE HAS TO ANSWER THESE QUESTIONS.<br> WE HAVE TO ANSWER THESE QUESTIONS.', 'visible': false },
        { 'q': 'VOCÊ PREFERE FRITAR OU ASSAR O FRANGO? (A CARNE / AS BATATAS)', 'r': 'DO YOU PREFER TO FRY OR BAKE THE CHICKEN?<br> DO YOU PREFER TO FRY OR BAKE THE MEAT?<br> DO YOU PREFER TO FRY OR BAKE THE POTATOES?', 'visible': false },
        { 'q': 'VOCÊ PODERIA FERVER UM POUCO DE ÁGUA PARA MIM? (PARA ELA / PARA NÓS)', 'r': 'COULD YOU BOIL A LITTLE WATER FOR ME?<br> COULD YOU BOIL A LITTLE WATER FOR HER?<br> COULD YOU BOIL A LITTLE WATER FOR US?', 'visible': false },
        { 'q': 'POR QUE VOCÊ NÃO CORTA ESTAS BATATAS? (ELA / ELE)', 'r': 'WHY DON\'T YOU CUT THESE POTATOES?<br> WHY DOESN\'T SHE CUT THESE POTATOES?<br> WHY DOESN\'T HE CUT THESE POTATOES?', 'visible': false },
        { 'q': 'PEÇA PARA A EMPREGADA LIMPAR MEU QUARTO, POR FAVOR. (A COZINHA / A SALA)', 'r': 'ASK THE MAID TO CLEAN MY BEDROOM / ROOM, PLEASE.<br> ASK THE MAID TO CLEAN THE KITCHEN, PLEASE.<br> ASK THE MAID TO CLEAN THE LIVING ROOM, PLEASE.', 'visible': false },
        { 'q': 'EU PRECISO APRENDER A MERGULHAR. (NADAR / SURFAR)', 'r': 'I NEED TO LEARN HOW TO DIVE.<br> I NEED TO LEARN HOW TO SWIM.<br> I NEED TO LEARN HOW TO SURF.', 'visible': false },
        { 'q': 'MINHA IRMÃ PINTA MUITO BEM. (MEU PRIMO / MINHA NORA / MEU SOGRO)', 'r': 'MY SISTER PAINTS VERY WELL.<br> MY COUSIN PAINTS VERY WELL.<br> MY DAUGHTER-IN-LAW PAINTS VERY WELL.<br> MY FATHER-IN-LAW PAINTS VERY WELL.', 'visible': false },
        { 'q': 'VOCÊ NÃO PRECISA EXPLICAR ISTO PARA MIM. (ELA / ELE / ELES)', 'r': 'YOU DON\'T NEED TO EXPLAIN THIS TO ME. <br> YOU DON\'T NEED TO EXPLAIN THIS TO HER.<br> YOU DON\'T NEED TO EXPLAIN THIS TO HIM. <br> YOU DON\'T NEED TO EXPLAIN THIS TO THEM.', 'visible': false },
        { 'q': 'ONDE VOCÊ GUARDA O LIQUIDIFICADOR? (BATEDEIRA / PANELA DE PRESSÃO / TALHERES)', 'r': 'WHERE DO YOU KEEP THE BLENDER?<br> WHERE DO YOU KEEP THE MIXER?<br> WHERE DO YOU KEEP THE PRESSURE COOKER?<br> WHERE DO YOU KEEP THE SILVERWARE?', 'visible': false },
        { 'q': 'EU GERALMENTE FAÇO A BARBA DE MANHÃ. (MEU PAI / MEU SOGRO / VOCÊ)', 'r': 'I USUALLY SHAVE IN THE MORNING.<br> MY FATHER USUALLY SHAVES IN THE MORNING.<br> MY FATHER-IN-LAW USUALLY SHAVES IN THE MORNING.<br> YOU USUALLY SHAVE IN THE MORNING.', 'visible': false },
        { 'q': 'MOSTRE-ME O DINHEIRO. (A ELA / A ELE / A ELES)', 'r': 'SHOW ME THE MONEY.<br> SHOW HER THE MONEY.<br> SHOW HIM THE MONEY.<br> SHOW THEM THE MONEY.', 'visible': false },
        { 'q': 'EU RARAMENTE ASSISTO TV À NOITE. (QUASE NUNCA / ALGUMAS VEZES)', 'r': 'I SELDOM WATCH TV AT NIGHT.<br> I HARDLY EVER WATCH TV AT NIGHT.<br> I SOMETIMES WATCH TV AT NIGHT.', 'visible': false },
        { 'q': 'O TELEFONE ESTÁ TOCANDO. VOCÊ PODE ATENDER PARA MIM? (PODERIA)', 'r': 'THE TELEPHONE IS RINGING. CAN YOU ANSWER IT FOR ME?<br> THE TELEPHONE IS RINGING. COULD YOU ANSWER IT FOR ME?', 'visible': false },
        { 'q': 'QUANTAS CARTAS VOCÊ PRECISA ENVIAR? (ESCREVER / LER / LEVAR AO CORREIO)', 'r': 'HOW MANY LETTERS DO YOU NEED TO SEND?<br> HOW MANY LETTERS DO YOU NEED TO WRITE?<br> HOW MANY LETTERS DO YOU NEED TO READ?<br> HOW MANY LETTERS DO YOU NEED TO TAKE TO THE POST OFFICE?', 'visible': false },
        { 'q': 'EU POSSO DIRIGIR SEU CARRO? (MOTO)', 'r': 'CAN I DRIVE YOUR CAR?<br> CAN I RIDE YOUR MOTORCYCLE?', 'visible': false },
        { 'q': 'EU GOSTO DE OUVIR MÚSICA EM MEU QUARTO. (ELA DELA / ELE DELE / NÓS NOSSO)', 'r': 'I LIKE TO LISTEN TO MUSIC IN MY BEDROOM / ROOM.<br> SHE LIKES TO LISTEN TO MUSIC IN HER BEDROOM / ROOM.<br> HE LIKES TO LISTEN TO MUSIC IN HIS BEDROOM / ROOM.<br> WE LIKE TO LISTEN TO MUSIC IN OUR BEDROOM / ROOM.', 'visible': false },
        { 'q': 'ELA PREFERE TIRAR UMA SONECA NO SOFÁ. (POLTRONA / CAMA)', 'r': 'SHE PREFERS TO TAKE A NAP ON THE COUCH.<br> SHE PREFERS TO TAKE A NAP IN THE ARMCHAIR.<br> SHE PREFERS TO TAKE A NAP IN BED / ON THE BED.', 'visible': false },
        { 'q': 'EU ESTOU COM FOME. VOCÊ PODE FAZER UM BOLO DE CHOCOLATE PARA MIM?', 'r': 'I\'M HUNGRY. CAN YOU MAKE A CHOCOLATE CAKE FOR ME? / CAN YOU MAKE ME A CHOCOLATE CAKE?', 'visible': false },
        { 'q': 'ABRA ESTA LATA PARA ELA COM ESTE NOVO ABRIDOR. (PARA ELE / PARA NÓS)', 'r': 'OPEN THIS CAN FOR HER WITH THIS NEW OPENER.<br> OPEN THIS CAN FOR HIM WITH THIS NEW OPENER.<br> OPEN THIS CAN FOR US WITH THIS NEW OPENER.', 'visible': false },
        { 'q': 'VOCÊ PODERIA ME TELEFONAR ÀS 20:00? (MEIO-DIA / 07:30 / 13:15)', 'r': 'COULD YOU CALL ME AT EIGHT PM / EIGHT O\'CLOCK?<br> COULD YOU CALL ME AT (TWELVE) NOON / TWELVE O\'CLOCK?<br> COULD YOU CALL ME AT SEVEN THIRTY AM / HALF PAST SEVEN?<br> COULD YOU CALL ME AT ONE FIFTEEN PM / A QUARTER PAST ONE?', 'visible': false },
        { 'q': 'PERGUNTE A ELE: VOCÊ GOSTA DE CORRER? (A ELA / A ELES)', 'r': 'ASK HIM: DO YOU LIKE TO RUN?<br> ASK HER: DO YOU LIKE TO RUN?<br> ASK THEM: DO YOU LIKE TO RUN?', 'visible': false },
        { 'q': 'E VOCÊ? VOCÊ PODE ME AJUDAR? (FALAR INGLÊS / COZINHAR)', 'r': 'AND YOU? / WHAT ABOUT YOU? CAN YOU HELP ME?<br> AND YOU? / WHAT ABOUT YOU? CAN YOU SPEAK ENGLISH?<br> AND YOU? / WHAT ABOUT YOU? CAN YOU COOK?', 'visible': false },
        { 'q': 'HÁ UMA CAMISA LIMPA PARA VOCÊ NO GUARDA-ROUPA.', 'r': 'THERE IS A CLEAN SHIRT FOR YOU IN THE CLOSET / WARDROBE.', 'visible': false },
        { 'q': 'HÁ DOIS GATOS NA ENTRADA DA GARAGEM. (TRÊS / UM / QUATRO)', 'r': 'THERE ARE TWO CATS ON THE DRIVEWAY.<br> THERE ARE THREE CATS ON THE DRIVEWAY.<br> THERE IS ONE CAT ON THE DRIVEWAY.<br> THERE ARE FOUR CATS ON THE DRIVEWAY.', 'visible': false }
      ]
    }
  ],
  'classies': [
    {
      'lesson': 'Unit 1A',
      'vocabulary': [
        { 'english': 'To sleep', 'translate': 'Dormir' },
        { 'english': 'To put (in/on)', 'translate': 'Colocar (dentro de/sobre)' },
        { 'english': 'To watch', 'translate': 'Assistir' },
        { 'english': 'To listen (to)', 'translate': 'Escutar/ouvir' },
        { 'english': 'TO take a nap', 'translate': 'Tirar uma soneca' },
        { 'english': 'Bedroom', 'translate': 'Quarto' },
        { 'english': 'Bed', 'translate': 'Cama' },
        { 'english': 'Mattress', 'translate': 'Colchão' },
        { 'english': 'Sheet', 'translate': 'Lençol' },
        { 'english': 'Blanket', 'translate': 'Cobertor' },
        { 'english': 'Closet', 'translate': 'Guarda-roupa/armário' },
        { 'english': 'Pillow', 'translate': 'Travesseiro' },
        { 'english': 'Pillowcase', 'translate': 'Fronha' },
        { 'english': 'Dining room', 'translate': 'Sala de jantar' },
        { 'english': 'Dinner table', 'translate': 'Mesa de jantar' },
        { 'english': 'Chair', 'translate': 'Cadeira' },
        { 'english': 'Living room', 'translate': 'Sala de estar' },
        { 'english': 'Sofa/couch', 'translate': 'Sofá' },
        { 'english': 'Armchair', 'translate': 'Poltrona' },
        { 'english': 'Cushion', 'translate': 'Almofada' },
        { 'english': 'Rug', 'translate': 'Tapete' },
        { 'english': 'Bookshelf', 'translate': 'Estante de livros' },
        { 'english': 'Wall unit', 'translate': 'Estante para TV, DVD, etc' },
        { 'english': 'TV/television', 'translate': 'Televisão' },
        { 'english': 'VCR', 'translate': 'Vídeo cassete' },
        { 'english': 'Sound system', 'translate': 'Aparelho de som' },
        { 'english': 'Radio', 'translate': 'Rádio' },
        { 'english': 'Movie/film', 'translate': 'Filme' },
        { 'english': 'Music', 'translate': 'Música' },
        { 'english': 'Picture', 'translate': 'Quadro/foto' }
      ]
    },
    {
      'lesson': 'Unit 1B',
      'vocabulary': [
        { 'english': 'To clean', 'translate': 'Limpar/arrumar' },
        { 'english': 'To shave', 'translate': 'Barbear-se/depilar-se' },
        { 'english': 'To comb', 'translate': 'Pentear' },
        { 'english': 'To brush', 'translate': 'Escovar' },
        { 'english': 'To keep', 'translate': 'Guardar/continuar' },
        { 'english': 'To take a bath', 'translate': 'Tomar banho (de banheira)' },
        { 'english': 'To take a shower', 'translate': 'Tomar banho (de chuveiro)' },
        { 'english': 'Comb', 'translate': 'Pente' },
        { 'english': 'Hair', 'translate': 'Cabelo' },
        { 'english': 'Hairbrush', 'translate': 'Escova de cabelo' },
        { 'english': 'Tooth/teeth', 'translate': 'Dente/dentes' },
        { 'english': 'Toothbrush', 'translate': 'Escova de dente' },
        { 'english': 'Toothpaste', 'translate': 'Pasta de dente' },
        { 'english': 'Dental floss', 'translate': 'Fio dental' },
        { 'english': 'Bathroom', 'translate': 'Banheiro' },
        { 'english': 'Bath towel', 'translate': 'Toalha de banho' },
        { 'english': 'Hand towel', 'translate': 'Toalha de rosto' },
        { 'english': 'Bathtub', 'translate': 'Banheira' },
        { 'english': 'Shower', 'translate': 'Chuveiro' },
        { 'english': 'Medicine cabinet', 'translate': 'Armarinho de banheiro' },
        { 'english': 'Deodorant', 'translate': 'Desodorante' },
        { 'english': 'Perfume', 'translate': 'Perfume' },
        { 'english': 'Shampoo', 'translate': 'Xampu' },
        { 'english': 'Hair conditioner', 'translate': 'Condicionador' },
        { 'english': 'Soap', 'translate': 'Sabonete/sabão' },
        { 'english': 'Shaving cream', 'translate': 'Creme de barbear' },
        { 'english': 'After shave', 'translate': 'Creme pós-barba' },
        { 'english': 'Razor', 'translate': 'Lâmina de barbear' },
        { 'english': 'Toilet paper', 'translate': 'Papel higiênico' },
        { 'english': 'Mirror', 'translate': 'Espelho' },
        { 'english': 'Maid', 'translate': 'Empregada' },
        { 'english': 'Clean', 'translate': 'Limpo (a)' },
        { 'english': 'Dirty', 'translate': 'Sujo (a)' }
      ]
    },
    {
      'lesson': 'Unit 1C',
      'vocabulary': [
        { 'english': 'To cook (for)', 'translate': 'Cozinhar (para)' },
        { 'english': 'To wash (for)', 'translate': 'Lavar (para)' },
        { 'english': 'To boil', 'translate': 'Ferver' },
        { 'english': 'To bake', 'translate': 'Assar' },
        { 'english': 'To fry', 'translate': 'Fritar' },
        { 'english': 'To stir', 'translate': 'Mexer líquidos/alimentos' },
        { 'english': 'To open', 'translate': 'Abrir' },
        { 'english': 'To make', 'translate': 'Fazer (elaborar/criar)' },
        { 'english': 'To cut', 'translate': 'Cortar' },
        { 'english': 'To use', 'translate': 'Usar' },
        { 'english': 'Kitchen', 'translate': 'Cozinha' },
        { 'english': 'Kitchen cabinet', 'translate': 'Armário de cozinha' },
        { 'english': 'Tablecloth', 'translate': 'Toalha de mesa' },
        { 'english': 'Sink', 'translate': 'Pia' },
        { 'english': 'Faucet/tap', 'translate': 'Torneira' },
        { 'english': 'Refrigerator/fridge', 'translate': 'Geladeira' },
        { 'english': 'Stove', 'translate': 'Fogão' },
        { 'english': 'Oven', 'translate': 'Forno' },
        { 'english': 'Microwave', 'translate': 'Forno de microondas' },
        { 'english': 'Dishwasher', 'translate': 'Máquina de lavar roupa' },
        { 'english': 'Pan', 'translate': 'Panela' },
        { 'english': 'Frying pan', 'translate': 'Frigideira' },
        { 'english': 'Baking pan', 'translate': 'Assadeira/forma de assar' },
        { 'english': 'Pressure cooker', 'translate': 'Panela de pressão' },
        { 'english': 'Ladle', 'translate': 'Concha' },
        { 'english': 'Can', 'translate': 'Lata' },
        { 'english': 'Silverware', 'translate': 'Talheres' },
        { 'english': 'Fork', 'translate': 'Garfo' },
        { 'english': 'Knife/knives', 'translate': 'Faca/facas' },
        { 'english': 'Spoon', 'translate': 'Colher' },
        { 'english': 'Dishes', 'translate': 'Louça' },
        { 'english': 'Plate', 'translate': 'Prato' },
        { 'english': 'Cup', 'translate': 'Xícara' },
        { 'english': 'Glass', 'translate': 'Copo' },
        { 'english': 'Bottle', 'translate': 'Garrafa' },
        { 'english': 'Chopping board', 'translate': 'Tábua de cortar alimentos' },
        { 'english': 'Mixer', 'translate': 'Batedeira' },
        { 'english': 'Blender', 'translate': 'Liquidificador' },
        { 'english': 'Opener', 'translate': 'Abridor' }
      ]
    },
    {
      'lesson': 'Unit 2A',
      'homework': [
        {
          'lesson': 'B',
          'title': 'Answer the following questions according to what you see in the drawing on page 32:',
          'questions': [
            { 'q': 'Is there toilet paper in the bathroom?', 'r': 'Yes, there is toilet paper beside the toilet/between the toilet and the bathtub.', 'visible': false },
            { 'q': 'Is there a sink in the bathroom?', 'r': 'Yes, there is a sink between the toilet and the shower.', 'visible': false },
            { 'q': 'Is there a toothbrush in the medicine cabinet?', 'r': 'No, there is a toothbrush on the sink.', 'visible': false },
            { 'q': 'Is there a bath towel in the bathroom?', 'r': 'No, the isn\'t.', 'visible': false },
            { 'q': 'Is there dental floss between the razor and the toothpaste?', 'r': 'No, there is an after shave between the razor and the toothpaste.', 'visible': false },
            { 'q': 'Is there a hand towel on the right side of the sink?', 'r': 'No, there is a hand towel on the left side of the sink.', 'visible': false },
            { 'q': 'Are there soaps on the sink?', 'r': 'No, there are three soaps in the bathtub.', 'visible': false },
            { 'q': 'Is there a comb in the bathroom?', 'r': 'Yes, there is a comb behind the toilet.', 'visible': false },
            { 'q': 'Is there a bathtub beside the toilet?', 'r': 'Yes, there is.', 'visible': false },
            { 'q': 'Is there a deodorant in the medicine cabinet?', 'r': 'No, there is a deodorant under the sink.', 'visible': false },
            { 'q': 'Is there a toothpaste on the sink?', 'r': 'No, there is a toothpaste in the medicine cabinet.', 'visible': false },
            { 'q': 'Are there perfumes in the medicine cabinet?', 'r': 'No, there aren\'t.', 'visible': false },
            { 'q': 'Is there a rug in the bathroom?', 'r': 'Yes, there is a rug in the middle of the bathroom/between the toilet and the shower/ in front of the sink/ in front of the bathtub.', 'visible': false },
            { 'q': 'Is there a shaving cream in the medicine cabinet?', 'r': 'No, there is a shaving cream among the soaps / in the bathtub.', 'visible': false }
          ]
        },
        {
          'lesson': 'C',
          'title': ' Turn the following sentences into negative and interrogative:',
          'questions': [
            { 'q': 'There are cushions on the couch.', 'r': '', 'visible': false },
            { 'q': 'There is an armchair in the living room.', 'r': '', 'visible': false },
            { 'q': 'There are sheets in the closet.', 'r': '', 'visible': false },
            { 'q': 'There are cans on the right side of the fridge.', 'r': '', 'visible': false },
            { 'q': 'There is a dining table in the middle of the dining room.', 'r': '', 'visible': false },
            { 'q': 'There is a chair in front of the bed.', 'r': '', 'visible': false },
            { 'q': 'There are hand towels among the bath towels.', 'r': '', 'visible': false },
            { 'q': 'There is a blender on the left side of the dishwasher.', 'r': '', 'visible': false },
            { 'q': 'There are forks among the spoons.', 'r': '', 'visible': false },
            { 'q': 'There are two faucets on the sink.', 'r': '', 'visible': false }
          ]
        }
      ],
      'vocabulary': [
        { 'english': 'There is', 'translate': 'Há / existe' },
        { 'english': 'There are', 'translate': 'Há / existem' },
        { 'english': 'In (the)', 'translate': 'Em / na(s) / no(s) (dentro de)' },
        { 'english': 'On (the)', 'translate': 'Em / na(s) / no(s)(em cima / sobre)' },
        { 'english': 'Under', 'translate': 'Embaixo de' },
        { 'english': 'Beside', 'translate': 'Ao lado de' },
        { 'english': 'Between', 'translate': 'Entre (duas coisas)' },
        { 'english': 'Among', 'translate': 'Entre (várias coisas)' },
        { 'english': 'Behind', 'translate': 'Atrás de' },
        { 'english': 'In front of', 'translate': 'Diante de / em frente à' },
        { 'english': 'In the middle of', 'translate': 'No meio de' },
        { 'english': 'Right (hand) side', 'translate': 'Lado direito' },
        { 'english': 'Left (hand) side', 'translate': 'Lado esquerdo' }
      ]
    },
    {
      'lesson': 'Unit 2B',
      'homework': [
        {
          'lesson': 'B',
          'title': ' Look at the map and answer the question:',
          'questions': [
            { 'q': 'Where\'s the church?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the mall?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the subway station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the zoo?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the newstand?', 'r': '', 'visible': false },
            { 'q': 'Is the restaurant near the flower shop?', 'r': '', 'visible': false },
            { 'q': 'Is the laundry far from the parking lot?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the gas station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the movie theater?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the restaurant', 'r': '', 'visible': false },
            { 'q': 'Where\'s the post office?', 'r': '', 'visible': false },
            { 'q': 'Is the hotel near the bus station?', 'r': '', 'visible': false },
            { 'q': 'Is the parking lot for from the zoo?', 'r': '', 'visible': false },
            { 'q': 'Where\'sthe police station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the thearter?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the hospital?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the museum?', 'r': '', 'visible': false },
            { 'q': 'Where\'s is the park?', 'r': '', 'visible': false },
            { 'q': 'Where\'s is the hotel?', 'r': '', 'visible': false }
          ]
        }
      ],
      'vocabulary': [
        { 'english': 'Zoo', 'translate': 'Zoológico' },
        { 'english': 'Mall', 'translate': 'Centro de compras / shopping center' },
        { 'english': 'Flower shop', 'translate': 'Floricultura' },
        { 'english': 'Newsstand', 'translate': 'Banca de jornal' },
        { 'english': 'Post office', 'translate': 'Correio' },
        { 'english': 'Bank', 'translate': 'Banco' },
        { 'english': 'Gas station', 'translate': 'Posto de gasolina' },
        { 'english': 'Parking lot', 'translate': 'Estacionamento' },
        { 'english': 'Bus station', 'translate': 'Estação / terminal de ônibus' },
        { 'english': 'Subway station', 'translate': 'Estação de metrô' },
        { 'english': 'Hotel', 'translate': 'Hotel' },
        { 'english': 'Museum', 'translate': 'Museu' },
        { 'english': 'Theater', 'translate': 'Teatro' },
        { 'english': 'Movies / movie  theater / cinema', 'translate': 'Cinema' },
        { 'english': 'Park', 'translate': 'Parque' },
        { 'english': 'Church', 'translate': 'Igreja' },
        { 'english': 'City hall', 'translate': 'Prefeitura' },
        { 'english': 'Police station', 'translate': 'Delegacia' },
        { 'english': 'Across (from)', 'translate': 'Em frente (à / ao)' },
        { 'english': 'Near', 'translate': 'Perto de' },
        { 'english': 'Next to', 'translate': 'Ao lado de / perto de / próximo à' },
        { 'english': 'Far (from)', 'translate': 'Longe (de)' },
        { 'english': '(On the) corner', 'translate': '(Na) esquina' },
        { 'english': 'Avenue (Ave.)', 'translate': 'Avenida' },
        { 'english': 'Street (St.)', 'translate': 'Rua' },
        { 'english': 'Road (Rd.)', 'translate': 'Via / estrada' }
      ]
    },
    {
      'lesson': 'Unit 2C',
      'vocabulary': [
        { 'english': 'to walk', 'translate': 'andar / caminhar' },
        { 'english': 'to turn right', 'translate': 'virar à direita' },
        { 'english': 'to turn left', 'translate': 'virar à esquerda' },
        { 'english': 'to go straight', 'translate': 'ir em frente' },
        { 'english': 'then', 'translate': 'então / depois' },
        { 'english': 'again', 'translate': 'novamente / de novo' },
        { 'english': 'block', 'translate': 'quadra' },
        { 'english': 'just past', 'translate': 'passando por / pelo (a)' }
      ]
    },
    {
      'lesson': 'Unit 3A',
      'vocabulary': [
        { 'english': 'Hour', 'translate': 'Hora' },
        { 'english': 'Minute', 'translate': 'Minuto' },
        { 'english': 'Second', 'translate': 'Segundo' },
        { 'english': 'Noon', 'translate': 'Meio-dia' },
        { 'english': 'Midnight', 'translate': 'Meia-noite' },
        { 'english': 'A.m. (ante-meridian)', 'translate': 'Antes do meio-dia' },
        { 'english': 'P.m. (post-meridian)', 'translate': 'Após o meio-dia' },
        { 'english': 'It\'s', 'translate': 'É / são' },
        { 'english': 'At', 'translate': 'Às (para horas) / ao / à' },
        { 'english': 'Until', 'translate': 'Até / até às / até ao' },
        { 'english': 'Past', 'translate': 'Passado' },
        { 'english': 'To', 'translate': 'Para' },
        { 'english': 'Early', 'translate': 'Cedo / adiantado (a)' },
        { 'english': 'Late', 'translate': 'Tarde / atrasado (a)' },
        { 'english': 'Already', 'translate': 'Já' }
      ]
    },
    {
      'lesson': 'Unit 3B',
      'vocabulary': [
        { 'english': 'To buy (for)', 'translate': 'Comprar (para)' },
        { 'english': 'To sell (to)', 'translate': 'Vender (para)' },
        { 'english': 'To give (to)', 'translate': 'Dar (para)' },
        { 'english': 'To pay', 'translate': 'Pagar' },
        { 'english': 'To spend', 'translate': 'Gastar / passar (tempo)' },
        { 'english': 'To rent', 'translate': 'Alugar' },
        { 'english': 'To give away', 'translate': 'Dar / doar' },
        { 'english': 'Cheap', 'translate': 'Barato (a)' },
        { 'english': 'Expensive', 'translate': 'Caro (a)' },
        { 'english': 'Present', 'translate': 'Presente' },
        { 'english': 'Eraser', 'translate': 'Borracha / apagador' },
        { 'english': 'Pen', 'translate': 'Caneta' },
        { 'english': 'Pencil', 'translate': 'Lápis' },
        { 'english': 'Paper', 'translate': 'Papel' },
        { 'english': 'Notebook', 'translate': 'Caderno' },
        { 'english': 'Flower', 'translate': 'Flor' },
        { 'english': 'More', 'translate': 'Mais' },
        { 'english': 'Some', 'translate': 'Algum(s) / alguma(s) / um pouco de' },
        { 'english': 'Any', 'translate': 'Algum(s) / alguma(s) / um pouco de / nenhum(a)' },
        { 'english': 'Bill', 'translate': 'Conta' },
        { 'english': 'Check', 'translate': 'Conta (restaurante)' },
        { 'english': 'Rent', 'translate': 'Aluguel' },
        { 'english': 'Light', 'translate': 'Luz / leve / claro (a)' },
        { 'english': 'Dark', 'translate': 'Escuro (a)' },
        { 'english': 'Money', 'translate': 'Dinheiro' },
        { 'english': 'Public', 'translate': 'Público (a)' },
        { 'english': 'Private', 'translate': 'Particular' },
        { 'english': 'For', 'translate': 'Para / por' },
        { 'english': 'Tomorrow', 'translate': 'Amanhã' },
        { 'english': 'Time', 'translate': 'Tempo' }
      ]
    },
    {
      'lesson': 'Unit 3C',
      'vocabulary': [
        { 'english': 'To cost', 'translate': 'Custar' },
        { 'english': 'On sale', 'translate': 'Em promoção / liquidação / oferta' },
        { 'english': 'For sale', 'translate': 'À venda' },
        { 'english': 'Price', 'translate': 'Preço' },
        { 'english': 'Coin', 'translate': 'Moeda' },
        { 'english': 'Change', 'translate': 'Troco' },
        { 'english': 'Which', 'translate': 'Qual / o (a) qual' },
        { 'english': 'How many', 'translate': 'Quantos / quantas (contáveis)' },
        { 'english': 'How much', 'translate': 'Quanto / quanta (incontáveis)' },
        { 'english': 'To go shopping', 'translate': 'Fazer compras' },
        { 'english': 'To pay cash', 'translate': 'Pagar em dinheiro / à vista' },
        { 'english': 'To pay in installments', 'translate': 'Pagar em prestações' },
        { 'english': 'Installment', 'translate': 'Prestação' },
        { 'english': 'Color', 'translate': 'Cor' },
        { 'english': 'White', 'translate': 'Branco' },
        { 'english': 'Black', 'translate': 'Preto' },
        { 'english': 'Blue', 'translate': 'Azul' },
        { 'english': 'Green', 'translate': 'Verde' },
        { 'english': 'Red', 'translate': 'Vermelho' },
        { 'english': 'Yellow', 'translate': 'Amarelo' },
        { 'english': 'Pink', 'translate': 'Cor de rosa' },
        { 'english': 'Gray', 'translate': 'Cinza' },
        { 'english': 'Purple', 'translate': 'Roxo / violeta' },
        { 'english': 'Brown', 'translate': 'Marrom' },
        { 'english': 'Orange', 'translate': 'Laranja / alaranjado' }
      ]
    },
    {
      'lesson': 'Unit 4A',
      'vocabulary': [
        { 'english': 'Can', 'translate': 'Poder / conseguir (fazer algo) /  ter habilidade ou' },
        { 'english': 'Can\'t', 'translate': 'Forma negativa do "can" (não poder...)' },
        { 'english': 'To run', 'translate': 'Correr' },
        { 'english': 'To drive', 'translate': 'Dirigir / ir de carro' },
        { 'english': 'To ride a horse', 'translate': 'Andar à cavalo' },
        { 'english': 'To ride a bicycle', 'translate': 'Andar de bicicleta' },
        { 'english': 'To dive', 'translate': 'Mergulhar' },
        { 'english': 'To surf', 'translate': 'Surfar' },
        { 'english': 'To paint', 'translate': 'Pintar' },
        { 'english': 'To sing', 'translate': 'Cantar' },
        { 'english': 'Football', 'translate': 'Futebol americano' },
        { 'english': 'Baseball', 'translate': 'Beisebol' },
        { 'english': 'Golf', 'translate': 'Golfe' },
        { 'english': 'Too', 'translate': 'Também / demais (quando antes de adjetivo)' },
        { 'english': 'Also', 'translate': 'Também' },
        { 'english': 'Either', 'translate': 'Também (frases negativas)' },
        { 'english': 'What about', 'translate': 'E (para perguntar sobre algo)' }
      ]
    },
    {
      'lesson': 'Unit 4B',
      'vocabulary': [
          { 'english': 'Could', 'translate': 'Poderia / podia / pôde' },
          { 'english': 'Couldn\'t', 'translate': 'Não poderia / não podia / não pôde' },
          { 'english': 'To call', 'translate': 'Ligar para / chamar' },
          { 'english': 'To show', 'translate': 'Mostrar / passar no cinema, TV, etc' },
          { 'english': 'To ask', 'translate': 'Perguntar / pedir (a alguém)' },
          { 'english': 'To ask for', 'translate': 'Pedir' },
          { 'english': 'To answer', 'translate': 'Responder' },
          { 'english': 'To explain', 'translate': 'Explicar' },
          { 'english': 'To send', 'translate': 'Enviar / mandar' },
          { 'english': 'To ring', 'translate': 'Tocar' },
          { 'english': 'Question', 'translate': 'Questão / pergunta' },
          { 'english': 'Message', 'translate': 'Mensagem' },
          { 'english': 'Package', 'translate': 'Pacote' },
          { 'english': 'Favor', 'translate': 'Favor' },
          { 'english': 'Just', 'translate': 'Apenas / só / justo (a)' },
          { 'english': 'Me', 'translate': 'Mim / me' },
          { 'english': 'You', 'translate': 'Lhe / te / você' },
          { 'english': 'Him', 'translate': 'Lhe / o / ele' },
          { 'english': 'Her', 'translate': 'Lhe / a / ela' },
          { 'english': 'It', 'translate': 'Lhe (neutro)' },
          { 'english': 'Us', 'translate': 'Nos / nós' },
          { 'english': 'You', 'translate': 'Lhes / vocês' },
          { 'english': 'Them', 'translate': 'Os / as / los / las' }
      ]
    },
    {
      'lesson': 'Unit 4C',
      'vocabulary': [
          { 'english': 'Seldom', 'translate': 'Raramente' },
          { 'english': 'Ever', 'translate': 'Alguma vez' },
          { 'english': 'Hardly ever', 'translate': 'Quase nunca' },
          { 'english': 'Once', 'translate': 'Uma vez' },
          { 'english': 'Twice', 'translate': 'Duas vezes' },
          { 'english': 'Times', 'translate': 'Vezes' },
          { 'english': 'Three times', 'translate': 'Três vezes' },
          { 'english': 'Four times', 'translate': 'Quatro vezes' },
          { 'english': 'A day', 'translate': 'Por dia' },
          { 'english': 'A week', 'translate': 'Por semana' },
          { 'english': 'A month', 'translate': 'Por mês' },
          { 'english': 'A year', 'translate': 'Por ano' }
      ]
    },
    {
      'lesson': 'Orange Unit 1A',
      'vocabulary': [
          { 'english': 'To remember', 'translate': 'Lembrar-se de' },
          { 'english': 'To forget (about)', 'translate': 'Esquecer (de)' },
          { 'english': 'To start', 'translate': 'Começar' },
          { 'english': 'To finish', 'translate': 'Terminar' },
          { 'english': 'To lose', 'translate': 'Perder' },
          { 'english': 'To find', 'translate': 'Encontrar' },
          { 'english': 'To look for', 'translate': 'Procurar' },
          { 'english': 'Document', 'translate': 'Documento' },
          { 'english': 'Key', 'translate': 'Chave' },
          { 'english': 'Office', 'translate': 'Escritório' },
          { 'english': 'Desk', 'translate': 'Mesa de escritório / escrivaninha' },
          { 'english': 'Another', 'translate': 'Outro (a)' },
          { 'english': 'Other', 'translate': 'Outros (as)' },
          { 'english': 'Before', 'translate': 'Antes de' },
          { 'english': 'After', 'translate': 'Depois de' },
          { 'english': 'Course', 'translate': 'Curso' },
          { 'english': 'Job', 'translate': 'Emprego' },
          { 'english': 'Ride', 'translate': 'Carona' },
          { 'english': 'Worried', 'translate': 'Preocupado (a)' },
          { 'english': 'Yesterday', 'translate': 'Ontem' },
          { 'english': 'Yesterday morning', 'translate': 'Ontem de manhã' },
          { 'english': 'Yesterday afternoon', 'translate': 'Ontem de tarde' },
          { 'english': 'Yesterday evening', 'translate': 'Ontem à noitinha' },
          { 'english': 'Last night', 'translate': 'Ontem à noite / noite passada' },
          { 'english': 'The day before yesterday', 'translate': 'Anteontem' }
      ]
    },
    {
      'lesson': 'Orange Unit 1B',
      'vocabulary': [
          { 'english': 'To remember', 'translate': 'Lembrar-se de' },
          { 'english': 'To leave', 'translate': 'Deixar / partir / sair (de)' },
          { 'english': 'To arrive (at / from)', 'translate': 'Chegar (em / de)' },
          { 'english': 'To miss', 'translate': 'Sentir falta / saudades de / perder (não objeto)' },
          { 'english': 'To oversleep', 'translate': 'Perder a hora / dormir demais' },
          { 'english': 'To wake up', 'translate': 'Acordar' },
          { 'english': 'To get up', 'translate': 'Levantar' },
          { 'english': 'Alarm clock', 'translate': 'Despertador' },
          { 'english': 'Clock', 'translate': 'Relógio' },
          { 'english': 'Watch', 'translate': 'Relógio de pulso' },
          { 'english': 'In time', 'translate': 'A tempo' },
          { 'english': 'On time', 'translate': 'Na hora' },
          { 'english': 'Already', 'translate': 'Já' },
          { 'english': 'Still', 'translate': 'Ainda' },
          { 'english': 'Yet', 'translate': 'Ainda' },
          { 'english': 'Ago', 'translate': 'Atrás (tempo)' },
          { 'english': 'Hurry up', 'translate': 'Depressa' },
          { 'english': 'In a hurry', 'translate': 'Com pressa' },
          { 'english': 'I have no idea', 'translate': 'Eu não tenho nem ideia' }
      ]
    },
    {
      'lesson': 'Orange Unit 1C',
      'vocabulary': [
          { 'english': 'To remember', 'translate': 'Lembrar-se de' },
          { 'english': 'To believe (in)', 'translate': 'Acreditar / crer (em)' },
          { 'english': 'To trust (in)', 'translate': 'Confiar (em)' },
          { 'english': 'To lie (to)', 'translate': 'Mentir (para)' },
          { 'english': 'To promise (to)', 'translate': 'Prometer (para)' },
          { 'english': 'To make a promise', 'translate': 'Fazer uma promessa' },
          { 'english': 'To make up', 'translate': 'Inventar / criar / fazer as pazes' },
          { 'english': 'Truth', 'translate': 'Verdade ' },
          { 'english': 'True', 'translate': 'Verdadeiro (a)' },
          { 'english': 'Lie', 'translate': 'Mentira' },
          { 'english': 'Liar', 'translate': 'Mentiroso (a)' },
          { 'english': 'Angel', 'translate': 'Anjo' },
          { 'english': 'Ghost', 'translate': 'Fantasma' },
          { 'english': 'God', 'translate': 'Deus' },
          { 'english': 'Witch / witches', 'translate': 'Bruxa / bruxas' },
          { 'english': 'So far', 'translate': 'Por enquanto / até agora' },
          { 'english': 'Different (from)', 'translate': 'Diferente (de)' },
          { 'english': 'The same', 'translate': 'O (a) mesmo (a)' },
          { 'english': 'Anymore', 'translate': 'Mais (frases neg.)' },
          { 'english': 'Maybe', 'translate': 'Talvez' },
          { 'english': 'Many', 'translate': 'Muitos (as)' },
          { 'english': 'Much', 'translate': 'Muito (a)' },
          { 'english': 'I think so', 'translate': 'Eu acho que sim' },
          { 'english': 'I don\'t think so', 'translate': 'Eu acho que não' }
      ]
    },
    {
      'lesson': 'Orange Unit 2A',
      'vocabulary': [
        { 'english': 'To look (at)', 'translate': 'Olhar (para)' },
        { 'english': 'To smile (at)', 'translate': 'Sorrir (para)' },
        { 'english': 'To laugh (at)', 'translate': 'Rir (de)' },
        { 'english': 'Important', 'translate': 'Importante' },
        { 'english': 'Busy', 'translate': 'Ocupado (a)' },
        { 'english': 'Funny', 'translate': 'Engraçado (a)' },
        { 'english': 'If', 'translate': 'Se' },
        { 'english': 'All the time', 'translate': 'O tempo todo' },
        { 'english': 'A long time ago', 'translate': 'Há muito tempo atrás' },
        { 'english': 'Long ago', 'translate': 'Há tempos atrás' },
        { 'english': 'Last', 'translate': 'Último (a) / passado (a)' },
        { 'english': 'Last week', 'translate': 'Semana passada' },
        { 'english': 'Last month', 'translate': 'Mês passado' },
        { 'english': 'Last year', 'translate': 'Ano passado' },
        { 'english': 'In a good mood', 'translate': 'De bom humor' },
        { 'english': 'In a bad mood', 'translate': 'De mau humor' }
      ]
    },
    {
      'lesson': 'Orange Unit 2B',
      'vocabulary': [
        { 'english': 'Leader', 'translate': 'Líder' },
        { 'english': 'Player', 'translate': 'Jogador' },
        { 'english': 'Artist', 'translate': 'Artista' },
        { 'english': 'Composer', 'translate': 'Compositor (a)' },
        { 'english': 'Writer', 'translate': 'Escritor (a)' },
        { 'english': 'Director', 'translate': 'Diretor (a)' },
        { 'english': 'Producer', 'translate': 'Produtor (a)' },
        { 'english': 'Playwright', 'translate': 'Dramaturgo (a)' },
        { 'english': 'Race driver', 'translate': 'Piloto (corrida)' },
        { 'english': 'Suspense', 'translate': 'Suspense' },
        { 'english': 'Horror', 'translate': 'Terror' },
        { 'english': 'Action', 'translate': 'Ação' },
        { 'english': 'Drama', 'translate': 'Drama' },
        { 'english': 'Romance', 'translate': 'Romance' },
        { 'english': 'Adventure', 'translate': 'Aventura' },
        { 'english': 'Comedy', 'translate': 'Comédia' },
        { 'english': 'Documentary', 'translate': 'Documentário' },
        { 'english': 'Crime movie', 'translate': '(Filme) policial' },
        { 'english': 'Cartoon', 'translate': 'Desenho animado' },
        { 'english': 'Kind', 'translate': 'Tipo / bondoso (a)' },
        { 'english': 'What kind (of)', 'translate': 'Que tipo (de)' }
      ]
    },
    {
      'lesson': 'Orange Unit 2C',
      'vocabulary': [
        { 'english': 'There was', 'translate': 'Havia / existia' },
        { 'english': 'There were', 'translate': 'Havia / existiam' },
        { 'english': 'Building', 'translate': 'Prédio / edifício' },
        { 'english': 'Forest', 'translate': 'Floresta' },
        { 'english': 'Hill', 'translate': 'Colina' },
        { 'english': 'Mountain', 'translate': 'Montanha' },
        { 'english': 'Waterfall', 'translate': 'Cachoeira' },
        { 'english': 'River', 'translate': 'Rio' },
        { 'english': 'Lake', 'translate': 'Lago' },
        { 'english': 'Sea', 'translate': 'Mar' },
        { 'english': 'Bugs', 'translate': 'Insetos' },
        { 'english': 'Everybody / everyone', 'translate': 'Todo mundo / todos' },
        { 'english': 'Somebody / someone', 'translate': 'Alguém' },
        { 'english': 'Anybody / anyone', 'translate': 'Alguém / ninguém' },
        { 'english': 'Nobody / no one', 'translate': 'Ninguém' }
      ]
    },
    {
      'lesson': 'Orange Unit 2D',
      'vocabulary': [
        { 'english': 'I went sightseeing', 'translate': 'Eu visitei os pontos turísticos' },
        { 'english': 'Bridge', 'translate': 'Ponte' },
        { 'english': 'I would go', 'translate': 'Eu iria' },
        { 'english': 'Sharks', 'translate': 'Tubarões' },
        { 'english': 'Cute', 'translate': 'Bonitinha (o)' },
        { 'english': 'I wish you were here.', 'translate': 'Eu gostaria que você estivesse aqui' }
      ]
    },
    {
      'lesson': 'Orange Unit 3A',
      'vocabulary': [
        { 'english': 'To break', 'translate': 'Quebrar' },
        { 'english': 'To fall (off)', 'translate': 'Cair (de)' },
        { 'english': 'To hurt', 'translate': 'Machucar / doer / magoar' },
        { 'english': 'Finger', 'translate': 'Dedo da mão' },
        { 'english': 'Hand', 'translate': 'Mão' },
        { 'english': 'Arm', 'translate': 'Braço' },
        { 'english': 'Toe', 'translate': 'Dedo do pé' },
        { 'english': 'Foot / feet', 'translate': 'Pé / pés' },
        { 'english': 'Leg', 'translate': 'Perna' },
        { 'english': 'Cast', 'translate': 'Gesso / elenco de um filme, peça, etc.' },
        { 'english': 'Stairs', 'translate': 'Escada (de degraus)' },
        { 'english': 'Ladder', 'translate': 'Escada móvel' },
        { 'english': 'Did you ever?', 'translate': 'Você alguma vez?' }
      ]
    },
    {
      'lesson': 'Orange Unit 3B',
      'vocabulary': [
        { 'english': 'To fall asleep', 'translate': 'Adormecer / cair no sono' },
        { 'english': 'To have a cold', 'translate': 'Estar resfriado (a)' },
        { 'english': 'To take medicine', 'translate': 'Tomar remédio' },
        { 'english': 'To take a shot', 'translate': 'Tomar injeção' },
        { 'english': 'Health', 'translate': 'Saúde' },
        { 'english': 'Healthy', 'translate': 'Saudável' },
        { 'english': 'Sick', 'translate': 'Doente' },
        { 'english': 'Disease / illness', 'translate': 'Doença' },
        { 'english': 'Fever', 'translate': 'Febre' },
        { 'english': 'Cough', 'translate': 'Tosse' },
        { 'english': 'Sore throat', 'translate': 'Dor de garganta / garganta irritada' },
        { 'english': 'Pain', 'translate': 'Dor' },
        { 'english': 'Headache', 'translate': 'Dor de cabeça' },
        { 'english': 'Toothache', 'translate': 'Dor de dente' },
        { 'english': 'Earache ', 'translate': 'Dor de ouvido' },
        { 'english': 'Stomachache', 'translate': 'Dor de estômago' },
        { 'english': 'Backache', 'translate': 'Dor nas costas' },
        { 'english': 'Prescription', 'translate': 'Prescrição / receita médica' },
        { 'english': 'Aspirin', 'translate': 'Aspirina' },
        { 'english': 'Home remedy', 'translate': 'Remédio caseiro' },
        { 'english': 'Insomnia', 'translate': 'Insônia' },
        { 'english': 'High blood pressure', 'translate': 'Pressão alta' },
        { 'english': 'Low blood pressure', 'translate': 'Pressão baixa' }
      ]
    },
    {
      'lesson': 'Light Green Unit 1A',
      'vocabulary': [
        { 'english': 'to knock (on)', 'translate': 'bater (em)' },
        { 'english': 'to enter', 'translate': 'entrar em' },
        { 'english': 'to close', 'translate': 'fechar' },
        { 'english': 'to go in (into)', 'translate': 'entrar' },
        { 'english': 'to come in', 'translate': 'entrar' },
        { 'english': 'to go back', 'translate': 'voltar' },
        { 'english': 'to turn on', 'translate': 'ligar' },
        { 'english': 'to turn off', 'translate': 'desligar' },
        { 'english': 'to be silent', 'translate': 'ficar em silêncio' },
        { 'english': '(in) silence', 'translate': '(em) silêncio' },
        { 'english': 'curtain', 'translate': 'cortina' },
        { 'english': 'to draw the curtain', 'translate': 'abrir / fechar a cortina' },
        { 'english': 'once in a while', 'translate': 'de vez em quando' },
        { 'english': 'while', 'translate': 'enquanto' },
        { 'english': 'to make sure', 'translate': 'certificar-se / ter certeza' },
        { 'english': 'forgetful', 'translate': 'esquecido (a)' },
        { 'english': 'apparently', 'translate': 'aparentemente' },
        { 'english': 'market', 'translate': 'mercado' },
        { 'english': 'garage', 'translate': 'garagem' },
        { 'english': 'door', 'translate': 'porta' },
        { 'english': 'doorbell', 'translate': 'campainha' },
        { 'english': 'window', 'translate': 'janela' },
        { 'english': 'closed', 'translate': 'fechado (a)' }
      ]
    },
    {
      'lesson': 'Light Green Unit 1B',
      'vocabulary': [
        { 'english': 'to pull', 'translate': 'puxar' },
        { 'english': 'to push', 'translate': 'empurrar' },
        { 'english': 'to lock', 'translate': 'travar / trancar' },
        { 'english': 'to peep', 'translate': 'espiar' },
        { 'english': 'on purpose', 'translate': 'de propósito' },
        { 'english': 'used to', 'translate': 'costumava' },
        { 'english': 'from now on', 'translate': 'de agora em diante' },
        { 'english': 'it\'s about time', 'translate': 'já é hora' },
        { 'english': 'keyhole', 'translate': 'buraco da fechadura' },
        { 'english': 'peephole', 'translate': 'olho mágico' },
        { 'english': 'handle', 'translate': 'puxador / maçaneta / alça (de mala, xícara, etc.)' },
        { 'english': 'key ring', 'translate': 'chaveiro (de bolso)' },
        { 'english': 'locksmith', 'translate': 'chaveiro (profissão)' },
        { 'english': 'drawer ', 'translate': 'gaveta' },
        { 'english': 'padlock', 'translate': 'cadeado' },
        { 'english': 'gate', 'translate': 'portão' },
        { 'english': 'locked', 'translate': 'trancado (a)' },
        { 'english': 'heavy', 'translate': 'pesado (a)' },
        { 'english': 'basement', 'translate': 'porão (habitável)' },
        { 'english': 'cellar', 'translate': 'porão / adega' },
        { 'english': 'attic', 'translate': 'sótão' },
        { 'english': 'through', 'translate': 'através de / por' }
      ]
    },
    {
      'lesson': 'Light Green Unit 2A',
      'vocabulary': [
        { 'english': 'to apply (for)', 'translate': 'inscrever-se / candidatar-se (para)' },
        { 'english': 'to fill in / out', 'translate': 'preencher' },
        { 'english': 'to interview', 'translate': 'entrevistar' },
        { 'english': 'to hire ', 'translate': 'contratar' },
        { 'english': 'to fire', 'translate': 'demitir' },
        { 'english': 'to dismiss', 'translate': 'demitir / ignorar / rejeitar' },
        { 'english': 'to turn down', 'translate': 'rejeitar / recusar' },
        { 'english': 'to give (someone) a chance', 'translate': 'dar uma chance a alguém' },
        { 'english': 'one at a time', 'translate': 'um de cada vez' },
        { 'english': 'to take a chance (on)', 'translate': 'tentar / fazer uma tentativa /' },
        { 'english': 'company', 'translate': 'companhia / empresa' },
        { 'english': 'main office', 'translate': 'escritório central (matriz)' },
        { 'english': 'branch', 'translate': 'filial' },
        { 'english': 'employer', 'translate': 'empregador' },
        { 'english': 'employee', 'translate': 'empregado' },
        { 'english': 'résumé', 'translate': 'currículo' },
        { 'english': 'applicant', 'translate': 'candidato' },
        { 'english': 'application form', 'translate': 'formulário' },
        { 'english': 'interview', 'translate': 'entrevista' },
        { 'english': 'loan', 'translate': 'empréstimo' }
      ]
    },
    {
      'lesson': 'Light Green Unit 2B',
      'vocabulary': [
        { 'english': 'to publish', 'translate': 'publicar' },
        { 'english': 'to advertise', 'translate': 'anunciar' },
        { 'english': 'to offer', 'translate': 'oferecer' },
        { 'english': 'to place an advertisement (ad)', 'translate': 'colocar um anúncio' },
        { 'english': 'part time', 'translate': 'meio expediente' },
        { 'english': 'full time', 'translate': 'período integral' },
        { 'english': 'to work overtime', 'translate': 'trabalhar horas extras' },
        { 'english': 'to be out of a job ', 'translate': 'ficar / estar sem emprego' },
        { 'english': 'the day after tomorrow', 'translate': 'depois de amanhã' },
        { 'english': 'article ', 'translate': 'artigo (jornal, revista, etc)' },
        { 'english': 'advertisement (ad)', 'translate': 'anúncio' },
        { 'english': 'offer', 'translate': 'oferta' },
        { 'english': 'opening', 'translate': 'vaga (emprego)' },
        { 'english': 'report', 'translate': 'relatório' },
        { 'english': 'staff', 'translate': 'equipe de trabalho' },
        { 'english': 'computer', 'translate': 'computador' },
        { 'english': 'address', 'translate': 'endereço' },
        { 'english': 'zip code', 'translate': 'código postal (CEP)' },
        { 'english': 'available', 'translate': 'disponível' }
      ]
    }
  ]
}

export default createDados
