export const createDados = {
  'site': {
    'name': 'English Class',
    'slug': 'english',
    'pages': [
      { 'name': 'Vocabulary', 'url': '/vocabulary' },
      {
        'name': 'Dark Yellow',
        'menu': [
          { 'name': 'Lesson 1A', 'url': '/vocabulary?class=0' },
          { 'name': 'Lesson 1B', 'url': '/vocabulary?class=1' },
          { 'name': 'Lesson 1C', 'url': '/vocabulary?class=2' },
          { 'name': 'Lesson 2A', 'url': '/lesson?class=3' },
          { 'name': 'Lesson 2B', 'url': '/lesson?class=4' },
          { 'name': 'Lesson 2C', 'url': '/vocabulary?class=5' },
          { 'name': 'Lesson 3A', 'url': '/vocabulary?class=6' },
          { 'name': 'Lesson 3B', 'url': '/vocabulary?class=7' },
          { 'name': 'Lesson 3C', 'url': '/vocabulary?class=8' }
        ]
      }
    ]
  },
  'classies': [
    {
      'lesson': 'Unit 1A',
      'vocabulary': [
        { 'english': 'To sleep', 'translate': 'Dormir' },
        { 'english': 'To put (in/on)', 'translate': 'Colocar (dentro de/sobre)' },
        { 'english': 'To watch', 'translate': 'Assistir' },
        { 'english': 'To listen (to)', 'translate': 'Escutar/ouvir' },
        { 'english': 'TO take a nap', 'translate': 'Tirar uma soneca' },
        { 'english': 'Bedroom', 'translate': 'Quarto' },
        { 'english': 'Bed', 'translate': 'Cama' },
        { 'english': 'Mattress', 'translate': 'Colchão' },
        { 'english': 'Sheet', 'translate': 'Lençol' },
        { 'english': 'Blanket', 'translate': 'Cobertor' },
        { 'english': 'Closet', 'translate': 'Guarda-roupa/armário' },
        { 'english': 'Pillow', 'translate': 'Travesseiro' },
        { 'english': 'Pillowcase', 'translate': 'Fronha' },
        { 'english': 'Dining room', 'translate': 'Sala de jantar' },
        { 'english': 'Dinner table', 'translate': 'Mesa de jantar' },
        { 'english': 'Chair', 'translate': 'Cadeira' },
        { 'english': 'Living room', 'translate': 'Sala de estar' },
        { 'english': 'Sofa/couch', 'translate': 'Sofá' },
        { 'english': 'Armchair', 'translate': 'Poltrona' },
        { 'english': 'Cushion', 'translate': 'Almofada' },
        { 'english': 'Rug', 'translate': 'Tapete' },
        { 'english': 'Bookshelf', 'translate': 'Estante de livros' },
        { 'english': 'Wall unit', 'translate': 'Estante para TV, DVD, etc' },
        { 'english': 'TV/television', 'translate': 'Televisão' },
        { 'english': 'VCR', 'translate': 'Vídeo cassete' },
        { 'english': 'Sound system', 'translate': 'Aparelho de som' },
        { 'english': 'Radio', 'translate': 'Rádio' },
        { 'english': 'Movie/film', 'translate': 'Filme' },
        { 'english': 'Music', 'translate': 'Música' },
        { 'english': 'Picture', 'translate': 'Quadro/foto' }
      ]
    },
    {
      'lesson': 'Unit 1B',
      'vocabulary': [
        { 'english': 'To clean', 'translate': 'Limpar/arrumar' },
        { 'english': 'To shave', 'translate': 'Barbear-se/depilar-se' },
        { 'english': 'To comb', 'translate': 'Pentear' },
        { 'english': 'To brush', 'translate': 'Escovar' },
        { 'english': 'To keep', 'translate': 'Guardar/continuar' },
        { 'english': 'To take a bath', 'translate': 'Tomar banho (de banheira)' },
        { 'english': 'To take a shower', 'translate': 'Tomar banho (de chuveiro)' },
        { 'english': 'Comb', 'translate': 'Pente' },
        { 'english': 'Hair', 'translate': 'Cabelo' },
        { 'english': 'Hairbrush', 'translate': 'Escova de cabelo' },
        { 'english': 'Tooth/teeth', 'translate': 'Dente/dentes' },
        { 'english': 'Toothbrush', 'translate': 'Escova de dente' },
        { 'english': 'Toothpaste', 'translate': 'Pasta de dente' },
        { 'english': 'Dental floss', 'translate': 'Fio dental' },
        { 'english': 'Bathroom', 'translate': 'Banheiro' },
        { 'english': 'Bath towel', 'translate': 'Toalha de banho' },
        { 'english': 'Hand towel', 'translate': 'Toalha de rosto' },
        { 'english': 'Bathtub', 'translate': 'Banheira' },
        { 'english': 'Shower', 'translate': 'Chuveiro' },
        { 'english': 'Medicine cabinet', 'translate': 'Armarinho de banheiro' },
        { 'english': 'Deodorant', 'translate': 'Desodorante' },
        { 'english': 'Perfume', 'translate': 'Perfume' },
        { 'english': 'Shampoo', 'translate': 'Xampu' },
        { 'english': 'Hair conditioner', 'translate': 'Condicionador' },
        { 'english': 'Soap', 'translate': 'Sabonete/sabão' },
        { 'english': 'Shaving cream', 'translate': 'Creme de barbear' },
        { 'english': 'After shave', 'translate': 'Creme pós-barba' },
        { 'english': 'Razor', 'translate': 'Lâmina de barbear' },
        { 'english': 'Toilet paper', 'translate': 'Papel higiênico' },
        { 'english': 'Mirror', 'translate': 'Espelho' },
        { 'english': 'Maid', 'translate': 'Empregada' },
        { 'english': 'Clean', 'translate': 'Limpo (a)' },
        { 'english': 'Dirty', 'translate': 'Sujo (a)' }
      ]
    },
    {
      'lesson': 'Unit 1C',
      'vocabulary': [
        { 'english': 'To cook (for)', 'translate': 'Cozinhar (para)' },
        { 'english': 'To wash (for)', 'translate': 'Lavar (para)' },
        { 'english': 'To boil', 'translate': 'Ferver' },
        { 'english': 'To bake', 'translate': 'Assar' },
        { 'english': 'To fry', 'translate': 'Fritar' },
        { 'english': 'To stir', 'translate': 'Mexer líquidos/alimentos' },
        { 'english': 'To open', 'translate': 'Abrir' },
        { 'english': 'To make', 'translate': 'Fazer (elaborar/criar)' },
        { 'english': 'To cut', 'translate': 'Cortar' },
        { 'english': 'To use', 'translate': 'Usar' },
        { 'english': 'Kitchen', 'translate': 'Cozinha' },
        { 'english': 'Kitchen cabinet', 'translate': 'Armário de cozinha' },
        { 'english': 'Tablecloth', 'translate': 'Toalha de mesa' },
        { 'english': 'Sink', 'translate': 'Pia' },
        { 'english': 'Faucet/tap', 'translate': 'Torneira' },
        { 'english': 'Refrigerator/fridge', 'translate': 'Geladeira' },
        { 'english': 'Stove', 'translate': 'Fogão' },
        { 'english': 'Oven', 'translate': 'Forno' },
        { 'english': 'Microwave', 'translate': 'Forno de microondas' },
        { 'english': 'Dishwasher', 'translate': 'Máquina de lavar roupa' },
        { 'english': 'Pan', 'translate': 'Panela' },
        { 'english': 'Frying pan', 'translate': 'Frigideira' },
        { 'english': 'Baking pan', 'translate': 'Assadeira/forma de assar' },
        { 'english': 'Pressure cooker', 'translate': 'Panela de pressão' },
        { 'english': 'Ladle', 'translate': 'Concha' },
        { 'english': 'Can', 'translate': 'Lata' },
        { 'english': 'Silverware', 'translate': 'Talheres' },
        { 'english': 'Fork', 'translate': 'Garfo' },
        { 'english': 'Knife/knives', 'translate': 'Faca/facas' },
        { 'english': 'Spoon', 'translate': 'Colher' },
        { 'english': 'Dishes', 'translate': 'Louça' },
        { 'english': 'Plate', 'translate': 'Prato' },
        { 'english': 'Cup', 'translate': 'Xícara' },
        { 'english': 'Glass', 'translate': 'Copo' },
        { 'english': 'Bottle', 'translate': 'Garrafa' },
        { 'english': 'Chopping board', 'translate': 'Tábua de cortar alimentos' },
        { 'english': 'Mixer', 'translate': 'Batedeira' },
        { 'english': 'Blender', 'translate': 'Liquidificador' },
        { 'english': 'Opener', 'translate': 'Abridor' }
      ]
    },
    {
      'lesson': 'Unit 2A',
      'homework': [
        {
          'lesson': 'B',
          'title': 'Answer the following questions according to what you see in the drawing on page 32:',
          'questions': [
            { 'q': 'Is there toilet paper in the bathroom?', 'r': 'Yes, there is toilet paper beside the toilet/between the toilet and the bathtub.', 'visible': false },
            { 'q': 'Is there a sink in the bathroom?', 'r': 'Yes, there is a sink between the toilet and the shower.', 'visible': false },
            { 'q': 'Is there a toothbrush in the medicine cabinet?', 'r': 'No, there is a toothbrush on the sink.', 'visible': false },
            { 'q': 'Is there a bath towel in the bathroom?', 'r': 'No, the isn\'t.', 'visible': false },
            { 'q': 'Is there dental floss between the razor and the toothpaste?', 'r': 'No, there is an after shave between the razor and the toothpaste.', 'visible': false },
            { 'q': 'Is there a hand towel on the right side of the sink?', 'r': 'No, there is a hand towel on the left side of the sink.', 'visible': false },
            { 'q': 'Are there soaps on the sink?', 'r': 'No, there are three soaps in the bathtub.', 'visible': false },
            { 'q': 'Is there a comb in the bathroom?', 'r': 'Yes, there is a comb behind the toilet.', 'visible': false },
            { 'q': 'Is there a bathtub beside the toilet?', 'r': 'Yes, there is.', 'visible': false },
            { 'q': 'Is there a deodorant in the medicine cabinet?', 'r': 'No, there is a deodorant under the sink.', 'visible': false },
            { 'q': 'Is there a toothpaste on the sink?', 'r': 'No, there is a toothpaste in the medicine cabinet.', 'visible': false },
            { 'q': 'Are there perfumes in the medicine cabinet?', 'r': 'No, there aren\'t.', 'visible': false },
            { 'q': 'Is there a rug in the bathroom?', 'r': 'Yes, there is a rug in the middle of the bathroom/between the toilet and the shower/ in front of the sink/ in front of the bathtub.', 'visible': false },
            { 'q': 'Is there a shaving cream in the medicine cabinet?', 'r': 'No, there is a shaving cream among the soaps / in the bathtub.', 'visible': false }
          ]
        },
        {
          'lesson': 'C',
          'title': ' Turn the following sentences into negative and interrogative:',
          'questions': [
            { 'q': 'There are cushions on the couch.', 'r': '', 'visible': false },
            { 'q': 'There is an armchair in the living room.', 'r': '', 'visible': false },
            { 'q': 'There are sheets in the closet.', 'r': '', 'visible': false },
            { 'q': 'There are cans on the right side of the fridge.', 'r': '', 'visible': false },
            { 'q': 'There is a dining table in the middle of the dining room.', 'r': '', 'visible': false },
            { 'q': 'There is a chair in front of the bed.', 'r': '', 'visible': false },
            { 'q': 'There are hand towels among the bath towels.', 'r': '', 'visible': false },
            { 'q': 'There is a blender on the left side of the dishwasher.', 'r': '', 'visible': false },
            { 'q': 'There are forks among the spoons.', 'r': '', 'visible': false },
            { 'q': 'There are two faucets on the sink.', 'r': '', 'visible': false }
          ]
        }
      ],
      'vocabulary': [
        { 'english': 'There is', 'translate': 'Há / existe' },
        { 'english': 'There are', 'translate': 'Há / existem' },
        { 'english': 'In (the)', 'translate': 'Em / na(s) / no(s) (dentro de)' },
        { 'english': 'On (the)', 'translate': 'Em / na(s) / no(s)(em cima / sobre)' },
        { 'english': 'Under', 'translate': 'Embaixo de' },
        { 'english': 'Beside', 'translate': 'Ao lado de' },
        { 'english': 'Between', 'translate': 'Entre (duas coisas)' },
        { 'english': 'Among', 'translate': 'Entre (várias coisas)' },
        { 'english': 'Behind', 'translate': 'Atrás de' },
        { 'english': 'In front of', 'translate': 'Diante de / em frente à' },
        { 'english': 'In the middle of', 'translate': 'No meio de' },
        { 'english': 'Right (hand) side', 'translate': 'Lado direito' },
        { 'english': 'Left (hand) side', 'translate': 'Lado esquerdo' }
      ]
    },
    {
      'lesson': 'Unit 2B',
      'homework': [
        {
          'lesson': 'B',
          'title': ' Look at the map and answer the question:',
          'questions': [
            { 'q': 'Where\'s the church?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the mall?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the subway station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the zoo?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the newstand?', 'r': '', 'visible': false },
            { 'q': 'Is the restaurant near the flower shop?', 'r': '', 'visible': false },
            { 'q': 'Is the laundry far from the parking lot?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the gas station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the movie theater?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the restaurant', 'r': '', 'visible': false },
            { 'q': 'Where\'s the post office?', 'r': '', 'visible': false },
            { 'q': 'Is the hotel near the bus station?', 'r': '', 'visible': false },
            { 'q': 'Is the parking lot for from the zoo?', 'r': '', 'visible': false },
            { 'q': 'Where\'sthe police station?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the thearter?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the hospital?', 'r': '', 'visible': false },
            { 'q': 'Where\'s the museum?', 'r': '', 'visible': false },
            { 'q': 'Where\'s is the park?', 'r': '', 'visible': false },
            { 'q': 'Where\'s is the hotel?', 'r': '', 'visible': false }
          ]
        }
      ],
      'vocabulary': [
        { 'english': 'Zoo', 'translate': 'Zoológico' },
        { 'english': 'Mall', 'translate': 'Centro de compras / shopping center' },
        { 'english': 'Flower shop', 'translate': 'Floricultura' },
        { 'english': 'Newsstand', 'translate': 'Banca de jornal' },
        { 'english': 'Post office', 'translate': 'Correio' },
        { 'english': 'Bank', 'translate': 'Banco' },
        { 'english': 'Gas station', 'translate': 'Posto de gasolina' },
        { 'english': 'Parking lot', 'translate': 'Estacionamento' },
        { 'english': 'Bus station', 'translate': 'Estação / terminal de ônibus' },
        { 'english': 'Subway station', 'translate': 'Estação de metrô' },
        { 'english': 'Hotel', 'translate': 'Hotel' },
        { 'english': 'Museum', 'translate': 'Museu' },
        { 'english': 'Theater', 'translate': 'Teatro' },
        { 'english': 'Movies / movie  theater / cinema', 'translate': 'Cinema' },
        { 'english': 'Park', 'translate': 'Parque' },
        { 'english': 'Church', 'translate': 'Igreja' },
        { 'english': 'City hall', 'translate': 'Prefeitura' },
        { 'english': 'Police station', 'translate': 'Delegacia' },
        { 'english': 'Across (from)', 'translate': 'Em frente (à / ao)' },
        { 'english': 'Near', 'translate': 'Perto de' },
        { 'english': 'Next to', 'translate': 'Ao lado de / perto de / próximo à' },
        { 'english': 'Far (from)', 'translate': 'Longe (de)' },
        { 'english': '(On the) corner', 'translate': '(Na) esquina' },
        { 'english': 'Avenue (Ave.)', 'translate': 'Avenida' },
        { 'english': 'Street (St.)', 'translate': 'Rua' },
        { 'english': 'Road (Rd.)', 'translate': 'Via / estrada' }
      ]
    },
    {
      'lesson': 'Unit 2C',
      'vocabulary': [
        { 'english': 'to walk', 'translate': 'andar / caminhar' },
        { 'english': 'to turn right', 'translate': 'virar à direita' },
        { 'english': 'to turn left', 'translate': 'virar à esquerda' },
        { 'english': 'to go straight', 'translate': 'ir em frente' },
        { 'english': 'then', 'translate': 'então / depois' },
        { 'english': 'again', 'translate': 'novamente / de novo' },
        { 'english': 'block', 'translate': 'quadra' },
        { 'english': 'just past', 'translate': 'passando por / pelo (a)' }
      ]
    },
    {
      'lesson': 'Unit 3A',
      'vocabulary': [
        { 'english': 'Hour', 'translate': 'Hora' },
        { 'english': 'Minute', 'translate': 'Minuto' },
        { 'english': 'Second', 'translate': 'Segundo' },
        { 'english': 'Noon', 'translate': 'Meio-dia' },
        { 'english': 'Midnight', 'translate': 'Meia-noite' },
        { 'english': 'A.m. (ante-meridian)', 'translate': 'Antes do meio-dia' },
        { 'english': 'P.m. (post-meridian)', 'translate': 'Após o meio-dia' },
        { 'english': 'It\'s', 'translate': 'É / são' },
        { 'english': 'At', 'translate': 'Às (para horas) / ao / à' },
        { 'english': 'Until', 'translate': 'Até / até às / até ao' },
        { 'english': 'Past', 'translate': 'Passado' },
        { 'english': 'To', 'translate': 'Para' },
        { 'english': 'Early', 'translate': 'Cedo / adiantado (a)' },
        { 'english': 'Late', 'translate': 'Tarde / atrasado (a)' },
        { 'english': 'Already', 'translate': 'Já' }
      ]
    },
    {
      'lesson': 'Unit 3B',
      'vocabulary': [
        { 'english': 'To buy (for)', 'translate': 'Comprar (para)' },
        { 'english': 'To sell (to)', 'translate': 'Vender (para)' },
        { 'english': 'To give (to)', 'translate': 'Dar (para)' },
        { 'english': 'To pay', 'translate': 'Pagar' },
        { 'english': 'To spend', 'translate': 'Gastar / passar (tempo)' },
        { 'english': 'To rent', 'translate': 'Alugar' },
        { 'english': 'To give away', 'translate': 'Dar / doar' },
        { 'english': 'Cheap', 'translate': 'Barato (a)' },
        { 'english': 'Expensive', 'translate': 'Caro (a)' },
        { 'english': 'Present', 'translate': 'Presente' },
        { 'english': 'Eraser', 'translate': 'Borracha / apagador' },
        { 'english': 'Pen', 'translate': 'Caneta' },
        { 'english': 'Pencil', 'translate': 'Lápis' },
        { 'english': 'Paper', 'translate': 'Papel' },
        { 'english': 'Notebook', 'translate': 'Caderno' },
        { 'english': 'Flower', 'translate': 'Flor' },
        { 'english': 'More', 'translate': 'Mais' },
        { 'english': 'Some', 'translate': 'Algum(s) / alguma(s) / um pouco de' },
        { 'english': 'Any', 'translate': 'Algum(s) / alguma(s) / um pouco de / nenhum(a)' },
        { 'english': 'Bill', 'translate': 'Conta' },
        { 'english': 'Check', 'translate': 'Conta (restaurante)' },
        { 'english': 'Rent', 'translate': 'Aluguel' },
        { 'english': 'Light', 'translate': 'Luz / leve / claro (a)' },
        { 'english': 'Dark', 'translate': 'Escuro (a)' },
        { 'english': 'Money', 'translate': 'Dinheiro' },
        { 'english': 'Public', 'translate': 'Público (a)' },
        { 'english': 'Private', 'translate': 'Particular' },
        { 'english': 'For', 'translate': 'Para / por' },
        { 'english': 'Tomorrow', 'translate': 'Amanhã' },
        { 'english': 'Time', 'translate': 'Tempo' }
      ]
    },
    {
        'lesson': 'Unit 3C',
        'vocabulary': [
            { 'english': 'To cost', 'translate': 'Custar' },
            { 'english': 'On sale', 'translate': 'Em promoção / liquidação / oferta' },
            { 'english': 'For sale', 'translate': 'À venda' },
            { 'english': 'Price', 'translate': 'Preço' },
            { 'english': 'Coin', 'translate': 'Moeda' },
            { 'english': 'Change', 'translate': 'Troco' },
            { 'english': 'Which', 'translate': 'Qual / o (a) qual' },
            { 'english': 'How many', 'translate': 'Quantos / quantas (contáveis)' },
            { 'english': 'How much', 'translate': 'Quanto / quanta (incontáveis)' },
            { 'english': 'To go shopping', 'translate': 'Fazer compras' },
            { 'english': 'To pay cash', 'translate': 'Pagar em dinheiro / à vista' },
            { 'english': 'To pay in installments', 'translate': 'Pagar em prestações' },
            { 'english': 'Installment', 'translate': 'Prestação' },
            { 'english': 'Color', 'translate': 'Cor' },
            { 'english': 'White', 'translate': 'Branco' },
            { 'english': 'Black', 'translate': 'Preto' },
            { 'english': 'Blue', 'translate': 'Azul' },
            { 'english': 'Green', 'translate': 'Verde' },
            { 'english': 'Red', 'translate': 'Vermelho' },
            { 'english': 'Yellow', 'translate': 'Amarelo' },
            { 'english': 'Pink', 'translate': 'Cor de rosa' },
            { 'english': 'Gray', 'translate': 'Cinza' },
            { 'english': 'Purple', 'translate': 'Roxo / violeta' },
            { 'english': 'Brown', 'translate': 'Marrom' },
            { 'english': 'Orange', 'translate': 'Laranja / alaranjado' }
        ]
    }
  ]
}

export default createDados
