export const createDados = {
  'site': {
    'name': 'English Class',
    'slug': 'english',
    'pages': [
      { 'name': 'Vocabulario', 'url': '/vocabulary' },
      {
        'name': 'Dark Yellow',
        'menu': [
          { 'name': 'Lesson 1A', 'url': '/vocabulary?class=0' },
          { 'name': 'Lesson 2B', 'url': '/vocabulary?class=1' },
          { 'name': 'Lesson 3C', 'url': '/vocabulary?class=2' },
          { 'name': 'Lesson 2A', 'url': '/vocabulary?class=3' },
          { 'name': 'Lesson 2B', 'url': '/vocabulary?class=4' }
        ]
      }
    ]
  },
  'classies': [
    {
      'lesson': '1A',
      'vocabulary': [
        { 'english': 'To sleep', 'translate': 'Dormir' },
        { 'english': 'To put (in/on)', 'translate': 'Colocar (dentro de/sobre)' },
        { 'english': 'To watch', 'translate': 'Assistir' },
        { 'english': 'To listen (to)', 'translate': 'Escutar/ouvir' },
        { 'english': 'TO take a nap', 'translate': 'Tirar uma soneca' },
        { 'english': 'Bedroom', 'translate': 'Quarto' },
        { 'english': 'Bed', 'translate': 'Cama' },
        { 'english': 'Mattress', 'translate': 'Colchão' },
        { 'english': 'Sheet', 'translate': 'Lençol' },
        { 'english': 'Blanket', 'translate': 'Cobertor' },
        { 'english': 'Closet', 'translate': 'Guarda-roupa/armário' },
        { 'english': 'Pillow', 'translate': 'Travesseiro' },
        { 'english': 'Pillowcase', 'translate': 'Fronha' },
        { 'english': 'Dining room', 'translate': 'Sala de jantar' },
        { 'english': 'Dinner table', 'translate': 'Mesa de jantar' },
        { 'english': 'Chair', 'translate': 'Cadeira' },
        { 'english': 'Living room', 'translate': 'Sala de estar' },
        { 'english': 'Sofa/couch', 'translate': 'Sofá' },
        { 'english': 'Armchair', 'translate': 'Poltrona' },
        { 'english': 'Cushion', 'translate': 'Almofada' },
        { 'english': 'Rug', 'translate': 'Tapete' },
        { 'english': 'Bookshelf', 'translate': 'Estante de livros' },
        { 'english': 'Wall unit', 'translate': 'Estante para TV, DVD, etc' },
        { 'english': 'TV/television', 'translate': 'Televisão' },
        { 'english': 'VCR', 'translate': 'Vídeo cassete' },
        { 'english': 'Sound system', 'translate': 'Aparelho de som' },
        { 'english': 'Radio', 'translate': 'Rádio' },
        { 'english': 'Movie/film', 'translate': 'Filme' },
        { 'english': 'Music', 'translate': 'Música' },
        { 'english': 'Picture', 'translate': 'Quadro/foto' }
      ]
    },
    {
      'lesson': '1B',
      'vocabulary': [
        { 'english': 'To clean', 'translate': 'Limpar/arrumar' },
        { 'english': 'To shave', 'translate': 'Barbear-se/depilar-se' },
        { 'english': 'To comb', 'translate': 'Pentear' },
        { 'english': 'To brush', 'translate': 'Escovar' },
        { 'english': 'To keep', 'translate': 'Guardar/continuar' },
        { 'english': 'To take a bath', 'translate': 'Tomar banho (de banheira)' },
        { 'english': 'To take a shower', 'translate': 'Tomar banho (de chuveiro)' },
        { 'english': 'Comb', 'translate': 'Pente' },
        { 'english': 'Hair', 'translate': 'Cabelo' },
        { 'english': 'Hairbrush', 'translate': 'Escova de cabelo' },
        { 'english': 'Tooth/teeth', 'translate': 'Dente/dentes' },
        { 'english': 'Toothbrush', 'translate': 'Escova de dente' },
        { 'english': 'Toothpaste', 'translate': 'Pasta de dente' },
        { 'english': 'Dental floss', 'translate': 'Fio dental' },
        { 'english': 'Bathroom', 'translate': 'Banheiro' },
        { 'english': 'Bath towel', 'translate': 'Toalha de banho' },
        { 'english': 'Hand towel', 'translate': 'Toalha de rosto' },
        { 'english': 'Bathtub', 'translate': 'Banheira' },
        { 'english': 'Shower', 'translate': 'Chuveiro' },
        { 'english': 'Medicine cabinet', 'translate': 'Armarinho de banheiro' },
        { 'english': 'Deodorant', 'translate': 'Desodorante' },
        { 'english': 'Perfume', 'translate': 'Perfume' },
        { 'english': 'Shampoo', 'translate': 'Xampu' },
        { 'english': 'Hair conditioner', 'translate': 'Condicionador' },
        { 'english': 'Soap', 'translate': 'Sabonete/sabão' },
        { 'english': 'Shaving cream', 'translate': 'Creme de barbear' },
        { 'english': 'After shave', 'translate': 'Creme pós-barba' },
        { 'english': 'Razor', 'translate': 'Lâmina de barbear' },
        { 'english': 'Toilet paper', 'translate': 'Papel higiênico' },
        { 'english': 'Mirror', 'translate': 'Espelho' },
        { 'english': 'Maid', 'translate': 'Empregada' },
        { 'english': 'Clean', 'translate': 'Limpo (a)' },
        { 'english': 'Dirty', 'translate': 'Sujo (a)' }
      ]
    },
    {
      'lesson': '1C',
      'vocabulary': [
        { 'english': 'To cook (for)', 'translate': 'Cozinhar (para)' },
        { 'english': 'To wash (for)', 'translate': 'Lavar (para)' },
        { 'english': 'To boil', 'translate': 'Ferver' },
        { 'english': 'To bake', 'translate': 'Assar' },
        { 'english': 'To fry', 'translate': 'Fritar' },
        { 'english': 'To stir', 'translate': 'Mexer líquidos/alimentos' },
        { 'english': 'To open', 'translate': 'Abrir' },
        { 'english': 'To make', 'translate': 'Fazer (elaborar/criar)' },
        { 'english': 'To cut', 'translate': 'Cortar' },
        { 'english': 'To use', 'translate': 'Usar' },
        { 'english': 'Kitchen', 'translate': 'Cozinha' },
        { 'english': 'Kitchen cabinet', 'translate': 'Armário de cozinha' },
        { 'english': 'Tablecloth', 'translate': 'Toalha de mesa' },
        { 'english': 'Sink', 'translate': 'Pia' },
        { 'english': 'Faucet/tap', 'translate': 'Torneira' },
        { 'english': 'Refrigerator/fridge', 'translate': 'Geladeira' },
        { 'english': 'Stove', 'translate': 'Fogão' },
        { 'english': 'Oven', 'translate': 'Forno' },
        { 'english': 'Microwave', 'translate': 'Forno de microondas' },
        { 'english': 'Dishwasher', 'translate': 'Máquina de lavar roupa' },
        { 'english': 'Pan', 'translate': 'Panela' },
        { 'english': 'Frying pan', 'translate': 'Frigideira' },
        { 'english': 'Baking pan', 'translate': 'Assadeira/forma de assar' },
        { 'english': 'Pressure cooker', 'translate': 'Panela de pressão' },
        { 'english': 'Ladle', 'translate': 'Concha' },
        { 'english': 'Can', 'translate': 'Lata' },
        { 'english': 'Silverware', 'translate': 'Talheres' },
        { 'english': 'Fork', 'translate': 'Garfo' },
        { 'english': 'Knife/knives', 'translate': 'Faca/facas' },
        { 'english': 'Spoon', 'translate': 'Colher' },
        { 'english': 'Dishes', 'translate': 'Louça' },
        { 'english': 'Plate', 'translate': 'Prato' },
        { 'english': 'Cup', 'translate': 'Xícara' },
        { 'english': 'Glass', 'translate': 'Copo' },
        { 'english': 'Bottle', 'translate': 'Garrafa' },
        { 'english': 'Chopping board', 'translate': 'Tábua de cortar alimentos' },
        { 'english': 'Mixer', 'translate': 'Batedeira' },
        { 'english': 'Blender', 'translate': 'Liquidificador' },
        { 'english': 'Opener', 'translate': 'Abridor' }
      ]
    },
    {
      'lesson': '2A',
      'vocabulary': [
        { 'english': 'There is', 'translate': 'Há / existe' },
        { 'english': 'There are', 'translate': 'Há / existem' },
        { 'english': 'In (the)', 'translate': 'Em / na(s) / no(s) (dentro de)' },
        { 'english': 'On (the)', 'translate': 'Em / na(s) / no(s)(em cima / sobre)' },
        { 'english': 'Under', 'translate': 'Embaixo de' },
        { 'english': 'Beside', 'translate': 'Ao lado de' },
        { 'english': 'Between', 'translate': 'Entre (duas coisas)' },
        { 'english': 'Among', 'translate': 'Entre (várias coisas)' },
        { 'english': 'Behind', 'translate': 'Atrás de' },
        { 'english': 'In front of', 'translate': 'Diante de / em frente à' },
        { 'english': 'In the middle of', 'translate': 'No meio de' },
        { 'english': 'Right (hand) side', 'translate': 'Lado direito' },
        { 'english': 'Left (hand) side', 'translate': 'Lado esquerdo' }
      ]
    },
    {
      'lesson': '2B',
      'vocabulary': [
        { 'english': 'Zoo', 'translate': 'Zoológico' },
        { 'english': 'Mall', 'translate': 'Centro de compras / shopping center' },
        { 'english': 'Flower shop', 'translate': 'Floricultura' },
        { 'english': 'Newsstand', 'translate': 'Banca de jornal' },
        { 'english': 'Post office', 'translate': 'Correio' },
        { 'english': 'Bank', 'translate': 'Banco' },
        { 'english': 'Gas station', 'translate': 'Posto de gasolina' },
        { 'english': 'Parking lot', 'translate': 'Estacionamento' },
        { 'english': 'Bus station', 'translate': 'Estação / terminal de ônibus' },
        { 'english': 'Subway station', 'translate': 'Estação de metrô' },
        { 'english': 'Hotel', 'translate': 'Hotel' },
        { 'english': 'Museum', 'translate': 'Museu' },
        { 'english': 'Theater', 'translate': 'Teatro' },
        { 'english': 'Movies / movie  theater / cinema', 'translate': 'Cinema' },
        { 'english': 'Park', 'translate': 'Parque' },
        { 'english': 'Church', 'translate': 'Igreja' },
        { 'english': 'City hall', 'translate': 'Prefeitura' },
        { 'english': 'Police station', 'translate': 'Delegacia' },
        { 'english': 'Across (from)', 'translate': 'Em frente (à / ao)' },
        { 'english': 'Near', 'translate': 'Perto de' },
        { 'english': 'Next to', 'translate': 'Ao lado de / perto de / próximo à' },
        { 'english': 'Far (from)', 'translate': 'Longe (de)' },
        { 'english': '(On the) corner', 'translate': '(Na) esquina' },
        { 'english': 'Avenue (Ave.)', 'translate': 'Avenida' },
        { 'english': 'Street (St.)', 'translate': 'Rua' },
        { 'english': 'Road (Rd.)', 'translate': 'Via / estrada' }
      ]
    }

  ]
}

export default createDados
