export const createDadosVerbs = {
  'irregular': [
    {
      'verbs': [
        { 'base': 'Arise', 'past': 'Arose', 'parti': 'arisen', 'translate': 'surgir, erguer-se' },
        { 'base': 'Awake', 'past': 'Awoke', 'parti': 'awoken', 'translate': 'despertar' },
        { 'base': 'Be', 'past': 'Was, were', 'parti': 'been', 'translate': 'ser, estar' },
        { 'base': 'Bear', 'past': 'Bore', 'parti': 'borne', 'translate': 'suportar, ser portador de' },
        { 'base': 'Beat', 'past': 'Beat', 'parti': 'beaten', 'translate': 'bater' },
        { 'base': 'Become', 'past': 'Became', 'parti': 'become', 'translate': 'tornar-se' },
        { 'base': 'Befall', 'past': 'Befell', 'parti': 'befallen', 'translate': 'acontecer' },
        { 'base': 'Beget', 'past': 'Begot', 'parti': 'begotten, begot', 'translate': 'procriar, gerar' },
        { 'base': 'Begin', 'past': 'Began', 'parti': 'begun', 'translate': 'começar' },
        { 'base': 'Behold', 'past': 'Beheld', 'parti': 'beheld', 'translate': 'contemplar' },
        { 'base': 'Bend', 'past': 'Bent', 'parti': 'bent', 'translate': 'curvar' },
        { 'base': 'Bet', 'past': 'Bet', 'parti': 'bet', 'translate': 'apostar' },
        { 'base': 'Bid', 'past': 'Bid', 'parti': 'bid', 'translate': 'oferecer, fazer uma oferta' },
        { 'base': 'Bind', 'past': 'Bound', 'parti': 'bound', 'translate': 'unir, encadernar, obrigar-se' },
        { 'base': 'Bite', 'past': 'Bit', 'parti': 'bitten', 'translate': 'morder' },
        { 'base': 'Bleed', 'past': 'Bled', 'parti': 'bled', 'translate': 'sangrar, ter hemorragia' },
        { 'base': 'Blow', 'past': 'Blew', 'parti': 'blown', 'translate': 'assoprar, explodir' },
        { 'base': 'Break', 'past': 'Broke', 'parti': 'broken', 'translate': 'quebrar' },
        { 'base': 'Breed', 'past': 'Bred', 'parti': 'bred', 'translate': 'procriar, reproduzir' },
        { 'base': 'Bring', 'past': 'Brought', 'parti': 'brought', 'translate': 'trazer' },
        { 'base': 'Broadcast', 'past': 'Broadcast', 'parti': 'broadcast', 'translate': 'irradiar, transmitir' },
        { 'base': 'Build', 'past': 'Built', 'parti': 'built', 'translate': 'construir' },
        { 'base': 'Buy', 'past': 'Bought', 'parti': 'bought', 'translate': 'comprar' },
        { 'base': 'Cast', 'past': 'Cast', 'parti': 'cast', 'translate': 'atirar, deitar' },
        { 'base': 'Catch', 'past': 'Caught', 'parti': 'caught', 'translate': 'pegar, capturar' },
        { 'base': 'Choose', 'past': 'Chose', 'parti': 'chosen', 'translate': 'escolher' },
        { 'base': 'Cling', 'past': 'Clung', 'parti': 'clung', 'translate': 'aderir, segurar-se' },
        { 'base': 'Come', 'past': 'Came', 'parti': 'come', 'translate': 'vir' },
        { 'base': 'Cost', 'past': 'Cost', 'parti': 'cost', 'translate': 'custar' },
        { 'base': 'Creep', 'past': 'Crept', 'parti': 'crept', 'translate': 'rastejar' },
        { 'base': 'Cut', 'past': 'Cut', 'parti': 'cut', 'translate': 'cortar' },
        { 'base': 'Deal', 'past': 'Dealt', 'parti': 'dealt', 'translate': 'negociar, tratar' },
        { 'base': 'Dig', 'past': 'Dug', 'parti': 'dug', 'translate': 'cavocar' },
        { 'base': 'Do', 'past': 'Did', 'parti': 'done', 'translate': 'fazer **' },
        { 'base': 'Draw', 'past': 'Drew', 'parti': 'drawn', 'translate': 'tracionar, desenhar **' },
        { 'base': 'Drink', 'past': 'Drank', 'parti': 'drunk', 'translate': 'beber' },
        { 'base': 'Drive', 'past': 'Drove', 'parti': 'driven', 'translate': 'dirigir, ir de carro' },
        { 'base': 'Eat', 'past': 'Ate', 'parti': 'eaten', 'translate': 'comer' },
        { 'base': 'Fall', 'past': 'Fell', 'parti': 'fallen', 'translate': 'cair' },
        { 'base': 'Feed', 'past': 'Fed', 'parti': 'fed', 'translate': 'alimentar' },
        { 'base': 'Feel', 'past': 'Felt', 'parti': 'felt', 'translate': 'sentir, sentir-se' },
        { 'base': 'Fight', 'past': 'Fought', 'parti': 'fought', 'translate': 'lutar' },
        { 'base': 'Find', 'past': 'Found', 'parti': 'found', 'translate': 'achar, encontrar' },
        { 'base': 'Flee', 'past': 'Fled', 'parti': 'fled', 'translate': 'fugir, escapar' },
        { 'base': 'Fling', 'past': 'Flung', 'parti': 'flung', 'translate': 'arremessar' },
        { 'base': 'Fly', 'past': 'Flew', 'parti': 'flown', 'translate': 'voar, pilotar' },
        { 'base': 'Forbid', 'past': 'Forbade', 'parti': 'forbidden', 'translate': 'proibir' },
        { 'base': 'Forget', 'past': 'Forgot', 'parti': 'forgot, forgotten', 'translate': 'esquecer' },
        { 'base': 'Forgive', 'past': 'Forgave', 'parti': 'forgiven', 'translate': 'perdoar' },
        { 'base': 'Freeze', 'past': 'Froze', 'parti': 'frozen', 'translate': 'congelar, paralisar' },
        { 'base': 'Get', 'past': 'Got', 'parti': 'gotten, got', 'translate': 'obter **' },
        { 'base': 'Give', 'past': 'Gave', 'parti': 'given', 'translate': 'dar' },
        { 'base': 'Go', 'past': 'Went', 'parti': 'gone', 'translate': 'ir' },
        { 'base': 'Grind', 'past': 'Ground', 'parti': 'ground', 'translate': 'moer' },
        { 'base': 'Grow', 'past': 'Grew', 'parti': 'grown', 'translate': 'crescer, cultivar' },
        { 'base': 'Have', 'past': 'Had', 'parti': 'had', 'translate': 'ter, beber, comer' },
        { 'base': 'Hear', 'past': 'Heard', 'parti': 'heard', 'translate': 'ouvir' },
        { 'base': 'Hide', 'past': 'Hid', 'parti': 'hidden, hid', 'translate': 'esconder' },
        { 'base': 'Hit', 'past': 'Hit', 'parti': 'hit', 'translate': 'bater' },
        { 'base': 'Hold', 'past': 'Held', 'parti': 'held', 'translate': 'segurar' },
        { 'base': 'Hurt', 'past': 'Hurt', 'parti': 'hurt', 'translate': 'machucar' },
        { 'base': 'Keep', 'past': 'Kept', 'parti': 'kept', 'translate': 'guardar, manter' },
        { 'base': 'Know', 'past': 'Knew', 'parti': 'known', 'translate': 'saber, conhecer' },
        { 'base': 'Lay', 'past': 'Laid', 'parti': 'laid', 'translate': 'colocar em posição horizontal, assentar' },
        { 'base': 'Lead', 'past': 'Led', 'parti': 'led', 'translate': 'liderar' },
        { 'base': 'Leave', 'past': 'Left', 'parti': 'left', 'translate': 'deixar, partir' },
        { 'base': 'Lend', 'past': 'Lent', 'parti': 'lent', 'translate': 'dar emprestado' },
        { 'base': 'Let', 'past': 'Let', 'parti': 'let', 'translate': 'deixar, alugar' },
        { 'base': 'Lie', 'past': 'Lay', 'parti': 'lain', 'translate': 'deitar' },
        { 'base': 'Lose', 'past': 'Lost', 'parti': 'lost', 'translate': 'perder, extraviar' },
        { 'base': 'Make', 'past': 'Made', 'parti': 'made', 'translate': 'fazer, fabricar **' },
        { 'base': 'Mean', 'past': 'Meant', 'parti': 'meant', 'translate': 'significar, querer dizer' },
        { 'base': 'Meet', 'past': 'Met', 'parti': 'met', 'translate': 'encontrar, conhecer' },
        { 'base': 'Overcome', 'past': 'Overcame', 'parti': 'overcome', 'translate': 'superar' },
        { 'base': 'Overtake', 'past': 'Overtook', 'parti': 'overtaken', 'translate': 'alcançar, surpreender' },
        { 'base': 'Pay', 'past': 'Paid', 'parti': 'paid', 'translate': 'pagar' },
        { 'base': 'Put', 'past': 'Put', 'parti': 'put', 'translate': 'colocar' },
        { 'base': 'Quit', 'past': 'Quit', 'parti': 'quit', 'translate': 'abandonar' },
        { 'base': 'Read', 'past': 'Read', 'parti': 'read', 'translate': 'ler' },
        { 'base': 'Ride', 'past': 'Rode', 'parti': 'ridden', 'translate': 'andar' },
        { 'base': 'Ring', 'past': 'Rang', 'parti': 'rung', 'translate': 'tocar (campainha, etc.)' },
        { 'base': 'Rise', 'past': 'Rose', 'parti': 'risen', 'translate': 'subir, erguer-se' },
        { 'base': 'Run', 'past': 'Ran', 'parti': 'run', 'translate': 'correr, concorrer, dirigir' },
        { 'base': 'Saw', 'past': 'Sawed', 'parti': 'sawn', 'translate': 'serrar' },
        { 'base': 'Say', 'past': 'Said', 'parti': 'said', 'translate': 'dizer' },
        { 'base': 'See', 'past': 'Saw', 'parti': 'seen', 'translate': 'ver' },
        { 'base': 'Seek', 'past': 'Sought', 'parti': 'sought', 'translate': 'procurar obter, objetivar' },
        { 'base': 'Sell', 'past': 'Sold', 'parti': 'sold', 'translate': 'vender' },
        { 'base': 'Send', 'past': 'Sent', 'parti': 'sent', 'translate': 'mandar' },
        { 'base': 'Set', 'past': 'Set', 'parti': 'set', 'translate': 'pôr em determinada condição, marcar, ajustar **' },
        { 'base': 'Shake', 'past': 'Shook', 'parti': 'shaken', 'translate': 'sacudir, tremer' },
        { 'base': 'Shed', 'past': 'Shed', 'parti': 'shed', 'translate': 'soltar, deixar cair **' },
        { 'base': 'Shine', 'past': 'Shone', 'parti': 'shone', 'translate': 'brilhar, reluzir' },
        { 'base': 'Shoot', 'past': 'Shot', 'parti': 'shot', 'translate': 'atirar, alvejar' },
        { 'base': 'Show', 'past': 'Showed', 'parti': 'shown', 'translate': 'mostrar, exibir' },
        { 'base': 'Shrink', 'past': 'Shrank', 'parti': 'shrunk', 'translate': 'encolher, contrair' },
        { 'base': 'Shut', 'past': 'Shut', 'parti': 'shut', 'translate': 'fechar, cerrar' },
        { 'base': 'Sing', 'past': 'Sang', 'parti': 'sung', 'translate': 'cantar' },
        { 'base': 'Sink', 'past': 'Sank', 'parti': 'sunk', 'translate': 'afundar, submergir' },
        { 'base': 'Sit', 'past': 'Sat', 'parti': 'sat', 'translate': 'sentar' },
        { 'base': 'Slay', 'past': 'Slew', 'parti': 'slain', 'translate': 'matar, assassinar' },
        { 'base': 'Sleep', 'past': 'Slept', 'parti': 'slept', 'translate': 'dormir' },
        { 'base': 'Slide', 'past': 'Slid', 'parti': 'slid', 'translate': 'deslizar, escorregar' },
        { 'base': 'Sling', 'past': 'Slung', 'parti': 'slung', 'translate': 'atirar, arremessar' },
        { 'base': 'Speak', 'past': 'Spoke', 'parti': 'spoken', 'translate': 'falar' },
        { 'base': 'Spend', 'past': 'Spent', 'parti': 'spent', 'translate': 'gastar' },
        { 'base': 'Spin', 'past': 'Spun', 'parti': 'spun', 'translate': 'fiar, rodopiar' },
        { 'base': 'Spit', 'past': 'Spit, spat', 'parti': 'spit, spat', 'translate': 'cuspir' },
        { 'base': 'Spread', 'past': 'Spread', 'parti': 'spread', 'translate': 'espalhar' },
        { 'base': 'Spring', 'past': 'Sprang', 'parti': 'sprung', 'translate': 'fazer saltar' },
        { 'base': 'Stand', 'past': 'Stood', 'parti': 'stood', 'translate': 'parar de pé, agüentar' },
        { 'base': 'Steal', 'past': 'Stole', 'parti': 'stolen', 'translate': 'roubar' },
        { 'base': 'Stick', 'past': 'Stuck', 'parti': 'stuck', 'translate': 'cravar, fincar, enfiar' },
        { 'base': 'Sting', 'past': 'Stung', 'parti': 'stung', 'translate': 'picar (inseto)' },
        { 'base': 'Stink', 'past': 'Stank', 'parti': 'stunk', 'translate': 'cheirar mal' },
        { 'base': 'Strike', 'past': 'Struck', 'parti': 'struck', 'translate': 'golpear, desferir, atacar' },
        { 'base': 'String', 'past': 'Strung', 'parti': 'strung', 'translate': 'encordoar, amarrar' },
        { 'base': 'Strive', 'past': 'Strove', 'parti': 'striven', 'translate': 'esforçar-se, lutar' },
        { 'base': 'Swear', 'past': 'Swore', 'parti': 'sworn', 'translate': 'jurar, prometer, assegurar' },
        { 'base': 'Sweep', 'past': 'Swept', 'parti': 'swept', 'translate': 'varrer' },
        { 'base': 'Swim', 'past': 'Swam', 'parti': 'swum', 'translate': 'nadar' },
        { 'base': 'Swing', 'past': 'Swung', 'parti': 'swung', 'translate': 'balançar, alternar' },
        { 'base': 'Take', 'past': 'Took', 'parti': 'taken', 'translate': 'tomar **' },
        { 'base': 'Teach', 'past': 'Taught', 'parti': 'taught', 'translate': 'ensinar, dar aula' },
        { 'base': 'Tear', 'past': 'Tore', 'parti': 'torn', 'translate': 'rasgar, despedaçar' },
        { 'base': 'Tell', 'past': 'Told', 'parti': 'told', 'translate': 'contar' },
        { 'base': 'Think', 'past': 'Thought', 'parti': 'thought', 'translate': 'pensar' },
        { 'base': 'Throw', 'past': 'Threw', 'parti': 'thrown', 'translate': 'atirar, arremessar' },
        { 'base': 'Tread', 'past': 'Trod', 'parti': 'trodden', 'translate': 'pisar, trilhar' },
        { 'base': 'Undergo', 'past': 'Underwent', 'parti': 'undergone', 'translate': 'submeter-se a, suportar' },
        { 'base': 'Understand', 'past': 'Understood', 'parti': 'understood', 'translate': 'entender' },
        { 'base': 'Uphold', 'past': 'Upheld', 'parti': 'upheld', 'translate': 'sustentar, apoiar, defender' },
        { 'base': 'Wear', 'past': 'Wore', 'parti': 'worn', 'translate': 'vestir, usar, gastar' },
        { 'base': 'Win', 'past': 'Won', 'parti': 'won', 'translate': 'vencer, ganhar' },
        { 'base': 'Wind', 'past': 'Wound', 'parti': 'wound', 'translate': 'enrolar, rodar, dar corda' },
        { 'base': 'Write', 'past': 'Wrote', 'parti': 'written', 'translate': 'escrever, redigir' }
      ]
    }
  ]
}

export default createDadosVerbs
